/**
 * Rivet product copy — plain owner language. Prefer importing from here over scattering UI strings.
 */

import { RIVET_PRICING } from "@/lib/pricing-copy"
import {
  EMOTIONAL_PROMISE,
  PRODUCT_LOOP,
  PRODUCT_LOOP_SUMMARY,
  PRODUCT_POSITIONING,
} from "@/lib/product-voice"

export const COPY = {
  product: {
    promise: EMOTIONAL_PROMISE,
    positioning: PRODUCT_POSITIONING,
    arc: PRODUCT_LOOP,
    arcSummary: PRODUCT_LOOP_SUMMARY,
  },

  connect: {
    title: "Link your business first",
    description:
      "Rivet needs a real operation to attach to—otherwise there is no floor to read, no shifts to prove, and nothing to pull out of your head.",
    cta: "Open settings",
  },

  billing: {
    checkoutCanceledTitle: "Checkout was closed",
    checkoutCanceledBody: "Stripe did not charge your card. When you are ready, continue below to try again.",
    productName: RIVET_PRICING.productName,
    limitedFounderRelease: RIVET_PRICING.limitedFounderRelease,
    priceOnce: RIVET_PRICING.priceOnce,
    priceInstallment: RIVET_PRICING.priceInstallment,
    positioningShort: RIVET_PRICING.positioningShort,
    cta: RIVET_PRICING.cta,
    checkoutCta: RIVET_PRICING.checkoutCta,
    included: RIVET_PRICING.included,
    subscribeTitle: RIVET_PRICING.subscribeTitle,
    subscribeLead: RIVET_PRICING.subscribeLead,
    subscribeCardNote: RIVET_PRICING.subscribeCardNote,
    founderGrandfatherNote: RIVET_PRICING.founderGrandfatherNote,
    paymentOnceLabel: RIVET_PRICING.paymentOnceLabel,
    paymentInstallmentLabel: RIVET_PRICING.paymentInstallmentLabel,
  },

  setup: {
    eyebrow: "Step 1 · Your business",
    title: "Name the operation Rivet will remember",
    lead:
      "Name your business first—next you pick your type and Rivet installs starter plays, training, and shift checklists so the floor is not empty.",
    cardTitle: "Your business",
    cardDescription:
      "This is what plays, Training Center modules, and proof attach to. You can refine the name later in Settings.",
    nameLabel: "Business name",
    namePlaceholder: "e.g. Northside Cafe",
    industryLabel: "How do you mainly run?",
    footerHint: "Next: pick a business type—we install plays, training, and checklists automatically.",
    footerHintBeforeCheckout:
      "Next: Founder Lifetime Access checkout—then pick your business type and install starter plays.",
    submit: "Continue",
    submitting: "Creating your business…",
  },

  routeRecovery: {
    backOverview: "Back to Overview",
    segmentErrorTitle: "This view did not load",
    segmentErrorBody:
      "Your account is still signed in. You can retry, open Settings if you were linking a workspace, or return to Overview.",
    tryAgain: "Try again",
    openSettings: "Open settings",
    notFoundTitle: "That screen is not in Rivet",
    notFoundBody:
      "The address may be wrong or the page may have moved. Use the sidebar, or go back to Overview or Settings.",
    notFoundOverview: "Go to Overview",
    notFoundSettings: "Open settings",
  },

  settingsWorkspace: {
    title: "Your business",
    description:
      "Create the business record Rivet uses as operating memory. Until it exists, export and most modules stay empty on purpose—there is no operation to attach to yet.",
    nameLabel: "Business name",
    namePlaceholder: "e.g. Northside Cafe",
    nameHelper: "This is the label Rivet shows for your operation. You can change it later in Settings if needed.",
    submit: "Create business",
    working: "Creating…",
    linkedTitle: "Business linked",
    linkedLead: "Rivet is remembering",
    linkedTrail: "—plays, shifts, and scores live here now.",
    linkedHint: "Invited staff still need profile rows tied to this business; membership tooling is separate.",
    serverSessionRequired:
      "Rivet could not read an authenticated Supabase session for this request. Sign in again, then retry.",
    serverSessionRequiredBypass:
      "Dev mode could not save your workspace. Restart the dev server and try again, or add Supabase keys to .env.local for real persistence.",
    signInToContinue: "Go to sign in",
  },

  shell: {
    tagline: PRODUCT_POSITIONING,
    signedIn: "Signed in",
    accountMenu: "Account menu",
    openMenu: "Open menu",
    navigation: "Navigation",
    settings: "Settings",
    signOut: "Sign out",
  },

  nav: {
    overview: "Overview",
    proofOfTransfer: "Execution proof",
    realityCheck: "Capture how work happens",
    standards: "Plays",
    standardsCapture: "Capture a play",
    askRivet: "Ask Rivet",
    highFriction: "High friction",
    training: "Training Center",
    shifts: "Can the shift run clean?",
    team: "Backup on the floor",
    bottlenecks: "Things still chasing you",
    interruptions: "Still routing to you",
    escapePlan: "Escape readiness",
    businessBrain: "Business Brain",
    settings: "Settings",
    accountSection: "Account",
  },

  hero: {
    eyebrow: "Operating picture",
    preview: "Preview",
    relianceSub: "Higher = more still depends on you.",
    autonomyLabel: "Can you step away?",
    weekLabel: "Still routing to you",
    weekHint: "Logged this week",
    weekHoursLeak: (hours: number) => `≈ ${hours} h of your time`,
    verdictQuestion: "Can the business run without me?",
    trendLabel: "Escape readiness (7 days)",
    trendHint: "Higher bars = easier week without you",
    trendEmpty: "No history yet.",
    bands: {
      critical: "Very high load on you",
      fragile: "High load on you",
      improving: "Getting better",
      stable: "Mostly OK",
      transferable: "Low load on you",
    },
    notScoredBadge: "Not scored yet",
    rivetEmptyPrimary: "—",
    rivetEmptySub: "Capture reality, publish plays, or run a dependency read to see your Rivet Score.",
  },

  dashboard: {
    postCheckoutTitle: "Payment received",
    postCheckoutBody:
      "Stripe confirmed checkout. If anything still looks locked, wait a few seconds for your business to update, then refresh this page.",
    postCheckoutDismiss: "Dismiss",
    loadErrorTitle: "Overview could not load",
    loadErrorBody:
      "Your session is unchanged. Retry once—if this keeps happening, open Settings or sign out and back in while we check connectivity.",
    criticalHeading: "Needs your attention",
    criticalAllLink: "See all open issues",
    criticalEmpty: "Nothing urgent flagged right now.",
    badgeBottleneck: "Still chasing you",
    badgeStandard: "Play",
    badgeRisk: "Risk",
    badgeTraining: "Training",
    badgeGap: "Still in your head",
    statusOpen: "Open",
    statusProgress: "In motion",
    nextEyebrow: "Do this next",
    proofHeading: "Execution proof",
    proofFullLink: "See full proof",
    proofEmpty:
      "No completed checklist runs on record yet—finish opening or closing on the floor, then refresh.",
    proofWin: "Off your plate",
    teamHeading: "Training Center",
    teamLink: "Open Training Center",
    teamTrainingDone: "Modules finished",
    teamReadinessAvg: "Floor coverage",
    teamSignals: "What the score sees",
    teamSignalTeam: "People depth",
    teamSignalTrain: "Teaching depth",
    depthHeading: "What still depends on you",
    depthExpand: "See what drives your score",
    depthExpandHint: "optional detail",
    depthHeatHint: "Darker = more still depends on you in that area.",
    warningsHeading: "Heads up",
    metrics: {
      standards: "Plays published",
      training: "Training done",
      bottlenecks: "Open issues",
      onYou: "Waiting on you",
    },
    outcome: {
      eyebrow: "Rivet outcome",
      lead: "One score for whether the business holds without you—plus the days you could step away, what still routes to your phone, and the fastest moves to change that.",
      milestonesTitle: "Absence milestones",
      milestonePtsAway: (pts: number) => `${pts} pts away`,
      milestoneReached: "Unlocked",
      recentImprovementsTitle: "Recent improvements",
      absenceDaysGained: (days: number) =>
        `+${days} estimated owner-free ${days === 1 ? "day" : "days"} vs last period`,
      simulationEyebrow: "Simulation mode",
      simulationTitle: "What if you disappeared for five days?",
      simulationLead:
        "Run a day-by-day forecast from your plays, training, issues, and owner pulls—see where strain shows up before you take time off.",
      simulationCapacityLabel: "Owner-free window",
      simulationBreakLabel: "Strain likely",
      simulationFailureHint: (point: string) => `First stress point: ${point}`,
      capacityFailureNote: (point: string) => `Before strain: watch ${point.toLowerCase()}.`,
      escapePlanLink: "Full escape plan",
    },
    freedomHero: {
      question: "Can the business run without me?",
      lead: "Six numbers that tell you how close you are to stepping back—and what breaks first if you leave tomorrow.",
      ownerFreeCapacity: "Owner-free capacity",
      ownerFreeCapacityHint: "Estimated days before strain shows",
      escapeReadiness: "Escape readiness score",
      escapeReadinessHint: "Higher = more likely five days away holds",
      questionsPrevented: "Questions prevented",
      questionsPreventedHint: "This month via Ask Rivet",
      ownerHoursReturned: "Owner hours returned",
      ownerHoursReturnedHint: "Time not spent answering the floor",
      teamReadiness: "Team readiness",
      teamReadinessHint: "Floor coverage across Training Center",
      highestRisk: "Highest operational risk",
      highestRiskHint: "What breaks first if you step away",
    },
    deeperHeading: "Operating detail",
    deeperLead: "Rivet Score, owner pulls, plays, and execution proof—below your outcome score.",
    brainLink: "Business Brain timeline",
    pulseHeading: "Operating picture",
    pulse: {
      ownerInterruptions: "Routed back to you this week",
      proceduresMissing: "Knowledge still in your head",
      trainingCompletion: "Training completion",
      issuesUnresolved: "Unresolved issues",
      escapeReadiness: "Escape readiness",
      rivetScore: "Rivet Score",
    },
    pulseRivetHint: "Higher = more depends on you",
    pulseEscapeHint: "Higher = more likely five days away holds",
    biggestRisksTitle: "Biggest risks this week",
    biggestRisksSubtitle:
      "Ranked from dependency score, knowledge still in your head, training gaps, and what still routes back to you.",
    metricNoData: "No data yet",
    scoreInsufficientFounderLabel: "Not scored yet — capture a play, assign training, or log what pulls you back.",
    scoreInsufficientRiskCaption:
      "Publish a few plays, assign training, or log owner pulls so Rivet can score how fused the operation is to you.",
    executionProofEmpty:
      "No completed checklist runs on record yet—finish a daily run on the floor so execution shows up here.",
    executionProofRun: "Completed run",
    teamSignalsEmpty:
      "Category scores need Training Center assignments or readiness rows to describe people and training depth.",
    marketingDemoCaption: "Illustrative preview only—your live overview uses your business, not made-up numbers.",
    setupGateTitle: "Link your business to load this overview",
    setupGateBody:
      "Scores, heatmaps, and proof pull from your operating memory on the record. Until then, nothing here is estimated—we leave the numbers blank on purpose.",
    setupGateCta: "Open settings",
    setupGateSecondary: "Capture reality",
    setupGateFootnote:
      "The full overview—including transfer signals drawn from your business—loads after you link it in Settings.",
    setupScoreMessage:
      "Your Rivet Score appears after you link a business. We do not make up numbers for an empty operation.",
    setupCategoryHint: "Fills in once the business is linked.",
    setupFounderLabel: "Not measured without a linked business.",
    setupRiskCaption: "No floor read yet.",
    setupNextTitle: "Link your business",
    setupNextDesc: "Name the operation in Settings so Rivet can start remembering how it runs.",
    setupNextCta: "Open settings",
    coldStartTitle: "Business linked—now put reality on the record",
    coldStartBody:
      "Rivet reads from plays, Training Center, shifts, and open issues. With nothing logged yet, the score is only directional. Capture one play or run a dependency read so the dashboard reflects your real floor.",
    coldStartCtaStandards: "Browse starter plays",
    coldStartCtaReality: "Capture reality",
    premiumSetupEyebrow: PRODUCT_POSITIONING,
    premiumSetupTitle: "Finish setup to open your operating picture",
    premiumSetupBody:
      "The overview reads from a real business—plays, Training Center, shifts, and proof. Name your operation, choose how you run, then complete the dependency read.",
    premiumSetupCta: "Start guided setup",
    firstStandardTitle: "Capture your first play",
    firstStandardBody:
      "Your dependency read is on file, but nothing is written to the floor yet. One short capture pulls knowledge out of your head into something the team can run without texting you.",
    firstStandardCta: "Capture a play",
    errorNextTitle: "Could not load overview",
    errorNextDesc:
      "Something interrupted the data load. Your workspace is still safe—this is usually temporary. Try reloading, or open Settings if you were changing workspace details.",
    errorNextCta: "Try again",
    teamLinkTraining: "Open Training Center",
  },

  counters: {
    bottlenecks: "Open messes",
    weekInterrupts: "Routed to you this week",
    needsYou: "Waiting on you",
    trainingDone: "Modules done",
    standardDepth: "Plays fleshed out",
    standardsGapBadge: "Thin plays",
    standardsGapText:
      "Some plays still read too thin to hand off—tighten cash, open/close, and one quality spine first.",
    standardsGapLink: "Open plays",
  },

  heatmap: {
    title: "Score by area",
    subtitle: "Darker = more still depends on you in that area.",
  },

  issues: {
    metadataTitle: "Things still chasing you",
    eyebrow: "Off your texts",
    title: "Things still chasing you",
    description:
      "Problems repeated enough times that they deserve a system—not another text message.",
    logCta: "+ Quick capture",
    tabsAll: "Everything",
    tabsYou: "Needs you",
    tabsOpen: "Not cleared",
    tabsCleared: "Cleared",
    tabsAria: "Things still chasing you filters",
    backToAll: "Things still chasing you",
    detailFallbackTitle: "Things still chasing you",
    saveCta: "Save",
    emptyDescription:
      "Either the queue is clear or filters are hiding rows. When something blocks a play, log it here so the fix lives in operating memory—not in your texts.",
    emptyFilterTitle: "Nothing in this view.",
    starterEyebrow: "Examples",
    starterTitle: "What shows up here",
    starterLead: "Repeated problems get named once—then the team fixes the system, not your inbox.",
    starterExampleBadge: "Example",
    logFirstIssueCta: "+ Quick capture",
    painScoreLabel: "Pain score",
    painScoreHint: "0–100 from frequency, time cost, owner involvement, and recency.",
    painScorePreviewLabel: "Pain score preview",
    painScorePreviewHint: "Updates as you set severity and owner involvement.",
    painScoreDriverFrequency: "Frequency",
    painScoreDriverTimeCost: "Time cost",
    painScoreDriverOwner: "Owner involvement",
    painScoreDriverRecency: "Recency",
    painScoreFrequencyOnce: "First time logged with this title.",
    painScoreFrequencyRepeat: (count: number) => `${count} times in the last 30 days.`,
    painScoreTimeCostDetail: (severity: string) => `Severity: ${severity}.`,
    painScoreOwnerRequired: "Owner must decide before the team moves.",
    painScoreOwnerOptional: "Team can likely clear without owner.",
    painScoreRecencyDetail: (days: number) =>
      days <= 1 ? "Logged in the last day." : `${days} day(s) since logged.`,
    costEstimateTitle: "Estimated cost",
    costEstimateHint:
      "Modeled from severity, category, repeat frequency, and owner load—so you see money, not just noise.",
    costEstimateMonthlyLabel: "Monthly projection",
    costEstimateMonthlyShort: "Est.",
    costEstimateLabor: "Labor impact",
    costEstimateLostSales: "Lost sales",
    costEstimateOwnerTime: "Owner time",
    costEstimateLaborDetail: (minutes: number, hourly: number) =>
      `~${minutes} min team time per incident @ $${hourly}/hr.`,
    costEstimateLostSalesDetail: "Category + severity modeled refund, remake, and walk-away risk.",
    costEstimateOwnerDetail: (minutes: number, hourly: number) =>
      minutes > 0
        ? `~${minutes} min owner attention per incident @ $${hourly}/hr.`
        : "No owner minutes while resolved.",
    costEstimateIncidentsOnce: "Priced as 1 incident in the last 30 days.",
    costEstimateIncidentsRepeat: (count: number) =>
      `Priced at ${count} incidents in the last 30 days—repeats multiply the bleed.`,
    costEstimateResolvedNote: "Resolved—projection shows residual tail only; ongoing bleed stops.",
    costEstimateDisclaimer:
      "Estimates use default wage assumptions ($22/hr team, $85/hr owner opportunity). Adjust when you wire real payroll.",
    costEstimateListBleedLabel: "Unresolved issues — estimated monthly bleed",
    costEstimateListBleedHint: "Sum of modeled labor, lost sales, and owner time across open issues.",
    fixRecommendationTitle: "Recommended fix",
    fixRecommendationLead: "This issue repeated—Rivet mapped a play, training, and who should own the fix.",
    fixRecommendationRootCause: "Why it keeps coming back",
    fixRecommendationSuggestedPlay: "Suggested play",
    fixRecommendationSuggestedTraining: "Suggested training",
    fixRecommendationSuggestedOwner: "Suggested owner",
    fixRecommendationRepeatReduction: "Estimated reduction in repeats",
    fixRecommendationRepeatReductionValue: (percent: number) => `≈ ${percent}%`,
    fixRecommendationRepeatReductionHint: (count: number) =>
      `Based on ${count} logs in 30 days plus severity and owner load.`,
    fixRecommendationNone: "None matched yet",
    fixRecommendationRelatedExisting: (title: string) => `Related existing: ${title}`,
    fixRecommendationCreateCta: "Create fix",
    fixRecommendationCreating: "Creating draft…",
    fixRecommendationRepeatBadge: "Repeat · fix ready",
    hauntingWeekTitle: "Haunting this week",
    hauntingWeekHint: "Issues logged since Monday UTC—ranked by what keeps pulling you back.",
    hauntingWeekSortAria: "Sort haunting issues",
    hauntingWeekSortFrequency: "Frequency",
    hauntingWeekSortImpact: "Estimated impact",
    hauntingWeekSortTimeCost: "Time cost",
    hauntingWeekEmpty: "Nothing logged this week yet.",
    hauntingWeekFrequencyLabel: "Frequency",
    hauntingWeekImpactLabel: "Impact",
    hauntingWeekTimeCostLabel: "Time cost",
    hauntingWeekImpactShort: (score: number) => `Impact ${score}`,
    hauntingWeekNeedsYou: "Needs you",
    issueOwnerLabel: "Owner",
    issueOwnerPlaceholder: "Assign owner",
    issueOwnerUnassigned: "Unassigned",
    issueDueDateLabel: "Due date",
    issueStatusLabel: "Status",
    issueTitleLabel: "Title",
    issueTitlePlaceholder: "Short summary",
    issueDescriptionLabel: "Description",
    issueDescriptionPlaceholder: "What happened, what you tried, what you need next",
    issueCategoryLabel: "Category",
    issueSeverityLabel: "Severity",
    issueOwnerRequiredHint: "This needs you—the owner—to decide or act before the team can move on.",
    issueOwnerRequiredOverviewHint: "Only you can unblock (shows on Overview)",
    issueSaving: "Saving…",
    issueSaved: "Saved.",
    issueSaveChanges: "Save changes",
    issueReportedAt: "Reported",
    issueLinksTitle: "Linked items",
    issueLinksHint: "Connect this issue to the play, training, owner pull, or person it touches.",
    issueLinksEmpty: "Nothing linked yet—add context so the team knows where to look.",
    issueLinksAddKind: "Link type",
    issueLinksAddTarget: "Pick item",
    issueLinksAddTargetPlaceholder: "Choose…",
    issueLinksAddCta: "Add link",
    issueLinksAdding: "Adding…",
    issueLinksRemoveAria: (title: string) => `Remove link to ${title}`,
    quickCaptureCta: "+ Quick capture",
    quickCaptureTitle: "Quick capture",
    quickCaptureHint: "Save in under 10 seconds—add detail later if needed.",
    quickCaptureWhatHappened: "What happened?",
    quickCaptureWhatPlaceholder: "One line is enough—e.g. cooler alarm, remake queue, scheduling gap",
    quickCapturePeople: "People involved",
    quickCapturePeopleEmpty: "No team roster yet—capture names in the note for now.",
    quickCaptureTimeLost: "Time lost",
    quickCaptureVoiceNote: "Voice note",
    quickCaptureVoiceStop: "Stop recording",
    quickCaptureVoiceTranscribing: "Transcribing…",
    quickCaptureSave: "Save",
    quickCaptureSaving: "Saving…",
    lifecycleTitle: "Issue lifecycle",
    lifecycleHint: "From first log through fix, training, and dependency relief.",
    lifecycleStageLogged: "Issue logged",
    lifecycleStagePattern: "Pattern detected",
    lifecycleStageFix: "Suggested fix created",
    lifecycleStageTraining: "Training assigned",
    lifecycleStageProgress: "Progress tracked",
    lifecycleStageDependency: "Dependency score updated",
    lifecycleDetailLogged: "Captured and on the board.",
    lifecycleDetailPattern: (count: number) => `${count} repeat(s) in 30 days—system fix warranted.`,
    lifecycleDetailFix: "Play or training module linked to this issue.",
    lifecycleDetailTraining: (count: number) =>
      count === 1 ? "1 team member assigned." : `${count} team members assigned.`,
    lifecycleDetailProgress: "Status moved or training underway.",
    lifecycleDetailDependency: (score: number) => `Handoff score refreshed at ${score}.`,
    lifecycleAssignTrainingCta: "Assign suggested training",
    lifecycleAssigningTraining: "Assigning…",
    shiftSectionTitle: "Things still chasing you from this shift",
    shiftReportHint: "Opens Things still chasing you and is linked to this shift when you are in a run.",
    newMetadataTitle: "Full issue form",
    newEyebrow: "Off your texts",
    newTitle: "Full issue form",
    newDescription: "Put the block on paper before it becomes a 9pm text chain.",
    newConnectDesc: "Link your business first—then this saves to your floor.",
    newSuccessDescription:
      "Anyone on the team can record what is stuck. Flag when only you can move it—that keeps owner load visible instead of invisible.",
  },

  interruptions: {
    featureTitle: "Still routing to you",
    featureDescription:
      "Every approval, question, and decision that still lands on you shows where operating memory is thin.",
    metadataTitle: "Still routing to you",
    eyebrow: "Owner dependency",
    title: "Still routing to you",
    description:
      "Every approval, question, and decision that still lands on you shows where operating memory is thin.",
    noBizEyebrow: "Owner pulls",
    noBizTitle: "Still routing to you",
    noBizDesc:
      "Link the workspace first—then the team can log approvals, questions, and decisions that still route back to you.",
    logEyebrow: "Fast log",
    logTitle: "Log an owner pull",
    logDescription: "Two taps: what kind of pull, how long it burned, one honest line. Done.",
    logSaved: "Saved. It shows on the dashboard immediately.",
    dashboardCta: "Open dashboard",
    logCta: "Log another",
    weekStat: "This week (UTC Mon–Sun)",
    hoursLeak: "Estimated owner time",
    hoursLeakHint: "Sum of time estimates your team logged—rough, but directionally honest.",
    trendTitle: "14-day heat map",
    trendHint: "Each cell is one UTC day. Darker means more owner time lost—hover for details.",
    heatmapLegendLabel: "Intensity",
    heatmapInterruptionsLabel: "Owner pulls",
    heatmapTimeLostLabel: "Time lost",
    heatmapMostCommonIssueLabel: "Most common issue",
    heatmapNoCommonIssue: "None logged",
    kindsTitle: "What kind of pull",
    kindsHint: "Where decisions collapse back to you.",
    topLeaksTitle: "Top Leaks",
    topLeaksHint: "Repeat pulls ranked by owner time—and what to write down to stop them.",
    topLeakOccurrencesLabel: "Occurrences",
    topLeakOwnerTimeLabel: "Estimated owner time",
    topLeakSuggestedFixLabel: "Suggested fix",
    rolesTitle: "Most dependent roles",
    rolesHint: "Grouped by the role on the roster card—coarse, but it surfaces who’s stuck in your pocket.",
    peopleTitle: "Who logged the most",
    peopleHint: "Usually the people closest to the fire. Pair with Training Center and written plays.",
    recentTitle: "Latest on the record",
    recentHint: "Newest first. Names come from the team roster.",
    emptyTrend: "No interruptions logged in this window yet—when they start, the shape shows up here.",
    emptyTopLeaks: "No repeat leaks yet—when the same label shows up twice, it ranks here.",
    emptyRepeats: "No repeat leaks yet—when the same label shows up twice, it ranks here.",
    emptyRoles: "No role signal yet.",
    starterEyebrow: "Examples",
    starterTitle: "What gets logged here",
    starterLead:
      "These are the pulls that usually land on the owner—approvals, questions, judgment calls, and escalations.",
    starterExampleBadge: "Example",
    logFirstPullCta: "Log first pull",
    starterSectionHint: "Log your first pull to see live data here.",
    actionHint: "Log pulls in the moment—before memory rounds the edges.",
    minutesLabel: "Minutes on you",
    summaryLabel: "One-line label",
    summaryPlaceholder: "e.g. “Approve comp for call-out” or “Guest wants exception to policy”",
    detailLabel: "Optional context",
    detailPlaceholder: "What was tried, what was blocked—only if it helps the next fix.",
    kindLabel: "Type",
    urgencyLabel: "How urgent",
    sourceLabel: "How it reached you",
    channelTitle: "Channel breakdown",
    channelHint: "Where pulls find you—text, call, floor tap, Slack, email, or other.",
    severityTitle: "Pull severity",
    severityHint: "Estimated from time spent, urgency, and how often the same pull repeats in 14 days.",
    severityPreviewLabel: "Estimated severity",
    severityPreviewHint: "Uses time and urgency now. Repeat pulls raise severity once similar labels show up.",
    actionPlanTitle: "Recommended fix",
    actionPlanLead: "Rivet mapped this pull to a draft play, related docs, and who it affects—every pull becomes a system improvement.",
    actionPlanRelatedSop: "Related play",
    actionPlanRelatedModule: "Training module",
    actionPlanNoneFound: "None matched yet",
    actionPlanPeopleAffected: "People affected",
    actionPlanNoPeople: "No roster matches yet.",
    actionPlanDraftFix: "Draft fix",
    actionPlanEditDraft: "Review draft",
    actionPlanApprove: "Approve fix plan",
    actionPlanPublish: "Publish fix",
    actionPlanDismiss: "Dismiss",
    actionPlanOwnerOnlyHint: "Only the owner can approve and publish fixes.",
    actionPlanGenerating: "Building your fix plan…",
    actionPlanStatusDraft: "Draft",
    actionPlanStatusApproved: "Approved",
    actionPlanStatusPublished: "Published",
    actionPlanStatusDismissed: "Dismissed",
    submit: "Log it",
    submitting: "Saving…",
    dashboardStripCta: "Open the leak map",
    dashboardStripLoggedSuffix: "logged this week",
    unitPulls: "pulls",
    fixSuggestionsTitle: "Turn repeats into system fixes",
    fixSuggestionsLead:
      "Every repeat pull should improve the business—Rivet detects the root cause and suggests a play, video, training, and Ask Rivet. After you publish fixes, Rivet tracks whether pulls drop.",
    fixSuggestionBadge: "Recommended fix",
    fixSuggestionRootCause: "Root cause",
    fixSuggestionSuggestedFix: "Suggested fix",
    fixSuggestionSop: "Play",
    fixSuggestionTrainingModule: "Training module",
    fixSuggestionInterruptionsLabel: "Est. pulls prevented / mo",
    fixSuggestionTimeLabel: "Est. owner time recovered / mo",
    fixSuggestionCreatePlay: "Create play",
    fixSuggestionCreateModule: "Create module",
    fixSuggestionOperationalActions: "Operational improvements",
    fixSuggestionAskOverlap: (count: number) =>
      `${count} similar question(s) in Ask Rivet—align the play and floor answer.`,
    fixSuggestionImpactTracking:
      "After you publish a fix plan, Rivet compares repeat pulls before and after for 14 days.",
    fixSuggestionStartFixPlan: "Start fix plan",
    fixActionCreatePlay: "Create play",
    fixActionImprovePlay: "Improve existing play",
    fixActionAddMedia: "Add video example",
    fixActionAssignTraining: "Assign training",
    fixActionAssignTrainingExisting: (title: string) => `Assign training: ${title}`,
    fixActionAskRivet: "Wire Ask Rivet answer",
    fixActionAskRivetDetail: "Staff should self-serve before they ping you.",
    fixActionAskRivetMatchDetail: (count: number) =>
      `${count} similar Ask Rivet question(s)—verify the answer is on the floor.`,
    valueMetricsTitle: "Owner value",
    valueMetricsLead:
      "Time and money the business gets back when pulls stop routing to you—based on this week’s trend and recommended fixes.",
    valueMetricsHoursLabel: "Hours returned this week",
    valueMetricsBusinessLabel: "Estimated business value",
    valueMetricsBusinessHint: "Based on your hourly value × hours returned",
    valueMetricsBusinessEmpty: "Set your hourly value below to see dollar impact.",
    valueMetricsHourlyLabel: "Your hourly value (CAD)",
    valueMetricsHourlyPlaceholder: "e.g. 75",
    valueMetricsSaveHourly: "Save hourly value",
    valueMetricsSaving: "Saving…",
    valueMetricsHourlyInvalid: "Enter a valid hourly value (0 or greater).",
    valueMetricsSourceActual: "Fewer pulls logged than last week—actual time returned.",
    valueMetricsSourceProjected: "Projected from recommended fixes if you ship them this week.",
    valueMetricsSourceNone: "Log repeats and fixes to see recoverable time.",
    becameTitle: "This pull became",
    recTitle: "Recommended path",
    recMatchedPlay: (title: string) => `Matched existing play: ${title}`,
    recCreatePlay: "No matching play—create a new one",
    recMatchedTraining: (title: string) => `Matched training: ${title}`,
    recAssignTraining: (count: number) =>
      count >= 2 ? "Staff keep asking—assign training" : "Assign training for this pull",
    recAddMedia: "Add a video walkthrough to the play",
    recAskRivet: "Add an Ask Rivet answer so staff can self-serve",
    recAskRivetMatch: (count: number) =>
      `${count} similar Ask Rivet question(s)—verify the answer is on the floor`,
    systemImprovementsTitle: "Pulls turned into system fixes",
    systemImprovementsLead:
      "Every logged pull should become a play, Training Center assignment, or Ask Rivet answer—track what shipped and whether repeats drop.",
    systemImprovementsProgress: (done: number, total: number) => `${done} of ${total} system fixes shipped`,
    systemImprovementsPending: "Fix in progress—review draft and publish",
    systemImprovementsReview: "Log another pull",
  },

  operations: {
    metadataTitle: "Shifts",
    eyebrowOwner: "Proof on the record",
    titleOwner: "Can the shift run clean?",
    descOwner:
      "Opening and closing with the same checklist every time—so the play held is visible, not something only you remember.",
    eyebrowStaff: "Your shift",
    titleStaff: "Can the shift run clean?",
    descStaff: "Run open and close from your phone. The dated record is what keeps you out of the group chat.",
    noBizEyebrow: "Shift proof",
    noBizTitle: "Can the shift run clean?",
    noBizDesc: "When the business is linked, this is where today’s open and close live—with receipts.",
    floorLabel: "Today’s checklists",
  },

  training: {
    metadataTitle: "Training Center",
    noBizEyebrow: "Training Center",
    noBizTitle: "Training Center",
    noBizDesc: "Modules tied to how you actually run—readiness means something on the floor, not a checkbox.",
    eyebrow: "Training Center",
    title: "Training Center",
    description: "Staff readiness at a glance—assigned modules, quiz scores, certifications, and manager sign-offs.",
    newModule: "New module",
    modulesHeading: "Modules",
    emptyTitle: "No modules yet",
    emptyDesc: "Start where gaps show up most—open, cash, or guest recovery—and wire the plays people should run.",
    emptyCta: "First module",
    exampleEyebrow: "When modules exist",
    exampleDesc: "Progress and readiness pull from the same plays your team already has to hit.",
    teamSectionTitle: "Training Center",
    teamSectionLead:
      "Each person shows assigned modules, completion progress, quiz scores, certifications, skills ready or needing work, and manager sign-offs.",
    teamEmpty: "No staff on this workspace yet—when teammates have accounts, link them to this business from Settings.",
    teamLink: "Open settings",
    employeeCardReadiness: "Training score",
    employeeQuizScore: "Quiz score",
    employeeSkillsReady: "Skills ready",
    employeeSkillsNeedsWork: "Needs work",
    employeeAssignedModules: "Assigned modules",
    employeeManagerSignOffs: "Manager sign-offs",
    employeeSignOffPending: "Pending",
    employeeSignOffComplete: "Signed off",
    employeeNoSignOffs: "No sign-offs logged yet.",
    employeeDelegationHeading: "Skill readiness",
    employeeDelegationHint:
      "Calculated from play completion, quizzes, videos, manager observations, sign-offs, and certifications. Override any line if floor performance differs.",
    employeeModulesHeading: "Module progress",
    employeeNoModules: "No modules assigned yet.",
    employeeDonePlays: (n: number) => `Complete (${n})`,
    employeeRemainingPlays: (n: number) => `Remaining (${n})`,
    employeeAddModule: "Assign module",
    employeeChooseModule: "Choose a module…",
    employeeAssign: "Assign",
    employeeRemove: "Remove",
    employeeRemoveConfirm: (title: string) => `Remove “${title}” from this person?`,
    employeeSopFootnote: "Checking plays updates module progress automatically.",
    employeeExpandDetails: "Manage assignments & plays",
    employeeCollapseDetails: "Hide details",
    matrixLink: "Team readiness matrix",
    successionLink: "Succession map",
  },

  managerObservations: {
    timelineTitle: "Manager observations",
    timelineLead:
      "Floor notes from you—positive wins, coaching moments, and critical issues. These feed the manager observations readiness signal.",
    typeLabel: "Observation type",
    typePositive: "Positive",
    typeImprovement: "Improvement",
    typeCritical: "Critical issue",
    notesLabel: "Notes",
    notesPlaceholder: "What did you see on the floor?",
    submit: "Log observation",
    empty: "No observations logged yet.",
    loggedBy: (name: string) => `Logged by ${name}`,
  },

  businessBrain: {
    metadataTitle: "Business Brain timeline",
    eyebrow: "Operating memory",
    title: "Business Brain timeline",
    description:
      "A chronological feed of what changed—plays, training, certifications, Ask Rivet wins, fewer owner pulls, and Escape readiness shifts.",
    backToOverview: "Overview",
    filterAll: "All",
    emptyAll: "Nothing logged in the last 90 days yet. Publish plays, run training, and use Ask Rivet—the feed fills as the business learns.",
    emptyFilter: "No events in this category for the last 90 days.",
    kindSopChange: "SOP change",
    kindTraining: "Training",
    kindCertification: "Certification",
    kindQuestionPrevented: "Question prevented",
    kindInterruptionsReduced: "Interruptions reduced",
    kindEscapeReadiness: "Escape readiness",
  },

  successionMap: {
    metadataTitle: "Team succession map",
    eyebrow: "Coverage",
    title: "Team succession map",
    description:
      "Who owns each role on the floor, who backs them up, and where you still have single-point-of-failure risk.",
    backToTraining: "Training Center",
    columnRole: "Role",
    columnPrimary: "Primary owner",
    columnBackup: "Backup owner",
    columnRisk: "Risk level",
    unassigned: "Unassigned",
    emptyRoles: "Add roles your business depends on—opening, closing, shift lead, and more.",
    addRoleLabel: "New role",
    addRolePlaceholder: "e.g. Shift lead",
    addRoleCta: "Add role",
    riskHint:
      "Risk uses Training Center readiness: critical means no primary or no backup ready; low means both are floor-ready for the linked skill.",
    matrixLink: "Readiness matrix",
    successionLink: "Succession map",
  },

  readinessMatrix: {
    metadataTitle: "Team readiness matrix",
    eyebrow: "Capability",
    title: "Team readiness matrix",
    description:
      "Skills, plays, and certifications across your team—green is floor-ready, yellow is in progress, red is not trained, gray is not assigned.",
    backToTraining: "Back to Training Center",
    employeeRoleFilter: "Role",
    locationFilter: "Location",
    certificationFilter: "Certification",
    statusFilter: "Readiness status",
    allRowKinds: "All rows",
    allStatuses: "All statuses",
    rowColumn: "Skill / play / certification",
    noModules: "Add training modules and plays to populate the matrix.",
    noEmployees: "Add team members to see the readiness matrix.",
    noFilterResults: "No rows match these filters. Try widening your selection.",
    cellTitle: (employee: string, row: string, status: string) =>
      `${employee} · ${row}: ${status}`,
    quickAnswersTitle: "Instant answers",
    quickAnswersLead: "Tap a question to highlight the row and see who is ready.",
    quickAnswerNobody: "Nobody ready yet",
    highlighted: "Highlighted",
    moduleRoleFilter: "Filter by module role",
    allEmployeeRoles: "All employee roles",
    moduleColumn: "Module / skill",
  },

  trainingPortal: {
    metadataTitle: "My training",
    homeTitle: "My training",
    homeLead: "Complete assigned modules on your phone—video, checklist, quiz, and photo proof when required.",
    emptyTitle: "No modules assigned yet",
    emptyDesc: "When your manager assigns training or sends an invite link, modules show up here.",
    joinTitle: "Training invite",
    joinLead: "Sign in to start this module. Works best on your phone between shifts.",
    joinSignIn: "Sign in to start",
    joinCreateAccount: "Create account",
    inviteInvalid: "This invite link is invalid or expired. Ask your manager for a new one.",
    inviteWrongAccount: "This invite was sent to someone else. Sign in with the correct account.",
    inviteHeading: "Send to employee",
    inviteHint: "Share by email, SMS, or copy a link. They open staff training on their phone and complete each play.",
    inviteEmployee: "Assign to (optional)",
    inviteAnyone: "Anyone with the link",
    inviteEmail: "Email",
    invitePhone: "Phone (SMS)",
    inviteCopyLink: "Create invite link",
    inviteEmailBtn: "Send email",
    inviteSmsBtn: "Send SMS",
    inviteCopy: "Copy link",
    inviteCopied: "Copied",
    openPortal: "Staff portal",
    portalCtaLead: "Employees complete modules on their phone—video, checklist, quiz, and photos.",
  },

  staffPortal: {
    metadataTitle: "Staff portal",
    metadataDescription:
      "Complete training, run plays, ask Rivet, upload proof, and earn certifications—built for the floor.",
    brandTitle: "Rivet",
    navAria: "Staff portal navigation",
    navHome: "Home",
    navTrain: "Train",
    navAsk: "Ask",
    navCerts: "Certs",
    navPlays: "Plays",
    homeTitle: "Your shift",
    greeting: (name: string) => `Hey ${name}`,
    seeAll: "See all",
    progressLabel: "Your progress",
    progressPlays: "plays done",
    progressModules: "modules",
    progressCerts: "certs",
    proofHint: "Open a module to watch, complete steps, and upload photo proof when required.",
    askFullPage: "Full-screen Ask Rivet",
    recentlyCompletedTitle: "Recently completed",
    recentlyCompletedEmpty: "Finished plays and modules show up here.",
    staffOnlyFooter: "Staff portal — training & plays only",
    todayTrainingTitle: "Today's training",
    todayTrainingLead: "Finish assigned modules—video, checklist, quiz, and photo proof when required.",
    todayTrainingEmpty: "Nothing assigned right now. Check back when training is assigned.",
    todayTrainingPageTitle: "Today's training",
    askRivetTitle: "Ask Rivet",
    askRivetLead: "Natural-language answers from plays, training, media, and owner notes—without texting the owner.",
    askRivetHint: "Tap to ask under pressure",
    readinessTitle: "Readiness & credentials",
    readinessLead:
      "Readiness percentages reflect training, quizzes, proof uploads, manager sign-offs, observations, and certifications—no points or streaks.",
    readinessHomeTitle: "Shift readiness",
    readinessHomeCta: "Full breakdown",
    certsTitle: "My certifications",
    certsLead: "Earned after module completion, quizzes, proof uploads, and manager sign-off. Each includes a printable certificate.",
    certsEmpty: "No certifications yet—complete a module to earn your first badge.",
    certsInProgress: (n: number) => `${n} in progress`,
    certsInProgressHeading: "Certifications in progress",
    playsTitle: "Assigned plays",
    playsLead: (n: number) =>
      n === 0
        ? "Plays from your assigned modules show up here for quick reference on the floor."
        : `${n} play${n === 1 ? "" : "s"} linked to your training.`,
    playsEmpty: "No plays assigned yet.",
    playDone: "done",
    playReadTitle: "Play",
    playBack: "Plays",
    moduleBack: "Training",
    trainingComplete: "Complete in module",
    playReferenceLead: "Reference only — complete steps and upload proof in your training module.",
    playReferenceNote: "Step checkmarks here are for reading on the floor. Training progress is tracked in your module.",
    moduleCompleteTitle: "Module complete",
    moduleCompleteLead: "You finished every play in this module.",
    moduleCompleteCerts: "View certifications",
    moduleCompleteHome: "Back to home",
    playerProgressLabel: "Progress",
    markPlayComplete: "Mark play complete",
    playCompleted: "Completed",
    readyToComplete: "Ready to mark this play complete.",
    previousPlay: "Previous",
    nextPlay: "Next",
    finishPlayBeforeNext: "Finish this play before moving to the next one.",
    quizFailed: "Not quite — review the material and try again. All answers must be correct.",
    quizPassed: "Quiz passed",
    visualCheckTitle: "Visual check",
    visualCheckNote: "Reference only — compare good vs. bad examples on the floor.",
    knowledgeCheckTitle: "Knowledge check",
    submitQuiz: "Submit quiz",
    certContinueModule: "Continue module",
    certViewProgress: "View what's left",
    askNoAnswerLead: "Rivet couldn't find a verified answer. Try your assigned plays or ask your manager.",
    askBrowsePlays: "Browse assigned plays",
    askBrowseTraining: "Open training",
  },

  certifications: {
    profileHeading: "Certifications",
    profileEmpty: "No certifications earned yet.",
    badgeTitle: (label: string, certifiedAt: string) =>
      `${label} · certified ${new Date(certifiedAt).toLocaleDateString(undefined, { dateStyle: "medium" })}`,
    trackerHeading: "Certifications",
    trackerHint:
      "Earned after module completion, quizzes passed, required photo proof uploaded, and manager sign-off.",
    stepModule: "Module completed",
    stepQuiz: "Quizzes passed",
    stepProof: "Proof uploaded",
    stepSignOff: "Manager sign-off",
    signOffButton: "Sign off on floor",
    certifiedLabel: "Certified",
    viewCertificate: "View certificate",
    certificateAria: (name: string) => `Certificate of completion: ${name}`,
    certificateEyebrow: "Certificate of completion",
    certificatePresentedTo: "This certifies that",
    certificateForCompleting: "has successfully completed",
    certificateScore: "Training score",
    certificateScoreValue: (pct: number) => `${pct}%`,
    certificateScoreNa: "—",
    certificateDate: "Date completed",
    certificateManager: "Manager sign-off",
    certificateManagerLine: (name: string, at: string) =>
      `${name} · ${new Date(at).toLocaleDateString(undefined, { dateStyle: "medium" })}`,
    certificateManagerPending: "Pending manager sign-off",
    certificateFooter: "Issued through Rivet training",
    printButton: "Print certificate",
    exportButton: "Save as PDF",
    ownerCertificateTitle: "Certificate",
    staffCertificateBack: "My certifications",
    ownerCertificateBack: "Training Center",
  },

  team: {
    metadataTitle: "Backup on the floor",
    eyebrow: "Depth",
    title: "Backup on the floor",
    description: "Who exists beyond you, what they can run alone, and how Training Center lines up—so peak isn’t a solo act.",
    emptyEyebrow: "Roster",
    emptyTitle: "Backup list is still building",
    emptyDesc:
      "Teaching already uses the people on your business. This roster-wide view is next—use Training Center for per-person readiness today.",
    stubNote:
      "No fabricated roster cards here. When this page ships, it will pull the same real readiness data you already see under Teaching.",
    emptyTraining: "Open Training Center",
    emptySettings: "Business settings",
  },

  sops: {
    metadataTitle: "Plays",
    eyebrow: "Operating memory",
    title: "Plays",
    descNoBiz: "The plays someone can run without interpreting you—short enough to use on a hot line.",
    desc: "Runnable plays in plain language. When success and failure are explicit, fewer decisions boomerang to you.",
    starterTitle: "Starter plays",
    starterBody: "Drop in open, close, bar, bakery, or cash drafts—then tune for your gear, vendors, and house rules.",
    starterCta: "Open gallery",
    gallery: "Starter gallery",
    capture: "Capture a play",
    new: "New play",
    edit: "Edit play",
    backToPlays: "Back to plays",
    createPlay: "Create play",
    savePlay: "Save changes",
    emptyEyebrow: "First play",
    emptyTitle: "Start with what only you still run.",
    emptyDesc: "Pick the question your team asks you most—or grab a draft from the gallery and edit it to your line.",
    browseGallery: "Browse gallery",
    authorScratch: "Write from scratch",
    alertTitle: "No plays yet — you are the system",
    alertBody:
      "Without published plays, Training Center has nothing to attach to and shifts have nothing to score. Put open or cash in the library first—then the floor stops improvising under pressure.",
    exampleEyebrow: "When the library has meat",
    exampleDesc: "Audits and opening runs both trace back to the same plays—here is what that looks like filled in.",
    exampleOpeningTitle: "Opening tied to plays (example)",
  },

  templates: {
    metadataTitle: "Starter plays",
    back: "Back to plays",
    title: "Starter plays",
    description: "Industry packs and classics as drafts—tune to your line before anyone runs them under pressure.",
    noBizDesc:
      "Starters land in your play library. Link the operation in Settings, then install drafts in one pass.",
    heroBadge: "Starter gallery",
    heroTitle1: "Packs written for real floors.",
    heroTitle2: "Plus the open, close, cash, and bar starters you already know.",
    heroLead:
      "Each industry ships eight linked drafts—open, close, quality, guest expectations, onboarding, escalation, roles, and a shift checklist. Install one card or the whole pack; everything lands as a draft you own.",
    listEyebrow: "Plays",
    listTitle: "Starter gallery",
    listDesc: "Filter by industry or category. Rename, retune vendors, and check local law before these hit a live line.",
    emptyFilter: "Nothing in this slice.",
    emptyFilterLink: "all starters",
  },

  welcome: {
    dismiss: "Dismiss",
    region: "Welcome",
    onboardingAria: "Welcome strip",
    doneLine: "You already did the honest pass.",
    doneTitle: "The uncomfortable part is on paper—so you can fix it on purpose.",
    doneBody: "Re-open your dependency read when you need a reset, then keep moving load into plays, Training Center, and owner pulls logged.",
    reportAgain: "Open report again",
    capture: "Capture a play",
    todoEyebrow: "If you are carrying too much",
    todoTitle: "You are not “bad at delegating.” The work still routes through you.",
    todoBody:
      "Eight blunt questions, one straight read on how fused the operation is to you—no shame, no fluff. Then Rivet helps you pull answers out of your head into plays your team can run.",
    todoCta: "Five-minute dependency read",
    chipSettingsLinked: "Settings",
    chipSettingsUnlinked: "Link business first",
    chipBrowse: "Browse starter plays",
  },

  proofPage: {
    title: "Execution proof",
    lead: "Evidence the operation can carry load without routing every judgment through you—not vibes, what the record shows.",
    backOverview: "Operating picture",
    openStandards: "Open plays",
    unlinkedHeadline: "Execution proof attaches to your business",
    unlinkedLead:
      "Link the operation in Settings. Wins from shifts, Training Center depth, and cleared issues land here as they happen—no demo filler.",
  },

  proofPanel: {
    eyebrow: "Execution proof",
    signalMix: "Signal mix",
    signals: (n: number) => `${n} signals`,
    bucketTransferred: "Off your plate",
    bucketTransferredDesc: "Things the team proved they can carry.",
    bucketFragile: "Still uneven",
    bucketFragileDesc: "Moving, but not trustworthy yet under pressure.",
    bucketOwner: "On you",
    bucketOwnerDesc: "Still concentrated until plays, training, or clears happen.",
    bucketStable: "Steadier",
    bucketStableDesc: "Signals holding calmer as you reinforce structure.",
    bucketEmpty: "Nothing here right now.",
    productSurface: "Product surface",
    introTitle: "The same views your team runs",
    introBody:
      "Checklists, audits, Training Center depth, dependency—shown as proof, not mockups. Your workspace replaces this with live data.",
    illustrative: "Examples use fixed demo lines—your account shows your business.",
    introReceipts:
      "Each card ties to shift proof, readiness, bottlenecks, or Rivet Index history—not a wish list.",
  },

  coach: {
    unlinkedTitle: "Outside read needs a linked business",
    unlinkedLead:
      "This brief is built only from your workspace signals. Link the operation in Settings, then come back for a grounded read—nothing here is invented.",
    unlinkedCta: "Open settings",
    errorTitle: "Could not load Outside read",
    errorLead: "Try again in a moment. If it keeps failing, refresh the page or check your connection.",
    retryCta: "Try again",
  },

  onboarding: {
    questionProgress: (i: number, n: number) => `Question ${i} of ${n}`,
    introEyebrow: "Capture how work happens",
    reportEyebrow: "Dependency read",
    reportIndexLabel: "How fused you are to the operation",
    reportIndexHint:
      "Higher = more still rides on your judgment, memory, and presence—not because you want it that way, but because the system is not finished yet.",
    breakdownHeading: "Dependency breakdown",
    breakdownSubheading:
      "How each category contributes weighted points to your score. Tackle the highest bar first for the fastest drop.",
    leverageLabel: "Highest leverage action:",
    leverageImprovementPrefix: "Estimated score improvement:",
    leverageCta: "Start this fix",
    bandCritical: "Heavy load",
    bandStrained: "Strained",
    bandContained: "Earlier than it feels",
    interpretationHeading: "Rivet Interpretation",
    interpretationCritical: "Critical dependency",
    interpretationHiddenRisk: "Hidden risk",
    interpretationPredicted: "Predicted outcome",
    interpretationFirstAction: "Suggested first action",
    interpretationActionCta: "Start this fix",
    strengthsHeading: "Strengths detected",
    uncomfortableHeading: "The straight truth",
    stakesHeading: "If nothing changes",
    movesHeading: "Your first moves here",
    movesOpen: "Open →",
    persistIdle: "Saved on this device. Retake anytime.",
    persistSaving: "Saving to your workspace…",
    persistSaved: "Saved into your overview inputs.",
    persistSkipped: "Create your workspace first (Overview → guided setup), then save again to keep this in history.",
    persistError: "Could not save—your read is still here on this device.",
    retake: "Retake",
    backOverview: "Back to overview",
    livePreview: (n: number) => `Live preview index: ${n}/100`,
    begin: "Begin",
    continue: "Continue",
    seeReport: "See read",
    back: "Back",
    reportIntroCard1:
      "Rivet is the operating memory of your business—for owners who are tired of being the glue between what you meant and what happened on the floor.",
    reportIntroCard2: "We will not shame you for working hard. We will map where the load is structurally stuck—and what to capture first.",
  },

  readinessQuestions: [
    { field: "open_alone" as const, label: "Can they open alone?" },
    { field: "close_alone" as const, label: "Can they close alone?" },
    { field: "train_others" as const, label: "Can they teach the next person?" },
    { field: "handle_complaints" as const, label: "Can they handle a hard guest without you?" },
  ],

  readinessBadges: {
    not_ready: "Still needs you close",
    learning: "Building",
    ready_with_support: "OK if you are one text away",
    fully_ready: "Can own it",
  },

  ownerWizard: {
    intro: {
      title:
        "If you are wiped and still the answer key, that is not drama—that is the floor telling the truth.",
      lead:
        "Blunt questions, then a straight read of how much still routes through you—and what to bump first so the line can carry more without you as human middleware.",
      speed: "Under five minutes. Answer like nobody is grading you—because nobody is.",
    },
    days: {
      title: "How many days a week does the business own you?",
      subtitle: "Count the days you are mentally on—even when you are not on the line the whole time.",
      choices: [
        { value: "0-2" as const, label: "0–2 days", hint: "Part-time owner or mostly off floor" },
        { value: "3-4" as const, label: "3–4 days", hint: "Heavy week, but not seven-on" },
        { value: "5-6" as const, label: "5–6 days", hint: "The business owns most of your calendar" },
        { value: "7" as const, label: "7 days", hint: "No clean off switch yet" },
      ],
    },
    open: {
      title: "Can someone else open clean without you?",
      subtitle: "Not “they help sometimes”—can the place open right if you do not show?",
      choices: [
        { value: "yes" as const, label: "Yes", hint: "A trained opener can run start to finish" },
        { value: "sometimes" as const, label: "Sometimes", hint: "Holds until an exception hits" },
        { value: "no" as const, label: "No", hint: "It still routes through you" },
      ],
    },
    close: {
      title: "Can someone else close clean without you?",
      subtitle: "Cash, deposits, alarms, temps, cleanup—with you out of the building.",
      choices: [
        { value: "yes" as const, label: "Yes", hint: "A trained closer can finish safely" },
        { value: "sometimes" as const, label: "Sometimes", hint: "Depends on the night" },
        { value: "no" as const, label: "No", hint: "You are still closer of last resort" },
      ],
    },
    interrupts: {
      title: "How often does the team pull you out of flow?",
      subtitle: "Texts, shoulder taps, “quick questions” that break what you were doing.",
      choices: [
        { value: "rarely" as const, label: "Rarely" },
        { value: "weekly" as const, label: "A few times a week" },
        { value: "daily" as const, label: "Most days" },
        { value: "constant" as const, label: "All day", hint: "It barely stops" },
      ],
    },
    breaks: {
      title: "What wobbles first when you step away?",
      subtitle: "One honest sentence. If it is a chain, name the first domino.",
      labelSr: "What wobbles when you step away",
      placeholder:
        "e.g. Line speeds up but quality slips, or cash waits because only I know the vendor workaround.",
      footnote: "Optional—and the read is sharper when you name the crack.",
    },
    timeoff: {
      title: "Have you skipped real time off because the business cannot release you?",
      subtitle: "Not vacation photos—days you could actually go dark.",
      choices: [
        { value: "yes" as const, label: "Yes" },
        { value: "no" as const, label: "No" },
        {
          value: "prefer_not" as const,
          label: "Prefer not to say",
          hint: "We will still generate your read",
        },
      ],
    },
    standards: {
      title: "Are plays on paper—or mostly in your head?",
      subtitle: "What a new hire actually inherits on day one.",
      choices: [
        { value: "documented" as const, label: "Written", hint: "Runnable plays people can follow" },
        { value: "mixed" as const, label: "Mixed", hint: "Some written, lots of tribal knowledge" },
        { value: "verbal" as const, label: "Mostly in my head", hint: "“Ask the owner” is still a workflow" },
      ],
    },
    quality: {
      title: "Does quality still ride on one pair of hands?",
      subtitle: "When the “right” plate still needs a specific person on the line.",
      choices: [
        { value: "yes" as const, label: "Yes" },
        { value: "no" as const, label: "No", hint: "Quality holds across people" },
        { value: "unsure" as const, label: "Not sure", hint: "Depends on the day" },
      ],
    },
  },

  escape: {
    metadataTitle: "Escape readiness",
    eyebrow: "Owner-free capacity",
    title: "Escape readiness",
    desc:
      "Escape readiness scores whether a week away is plausible from live plays, Training Center, owner pulls, and staffing—then guided moves to grow Owner-free capacity.",
    noBizEyebrow: PRODUCT_LOOP_SUMMARY,
    noBizTitle: "Escape readiness",
    noBizDesc: `Link your business to score Escape readiness and Owner-free capacity—${PRODUCT_LOOP_SUMMARY}.`,
  },

  escapeReadiness: {
    simulateOwnerAbsence: "Simulate owner absence",
    simulationTitle: "Simulate owner absence",
    simulationLead:
      "Day-by-day forecast using play coverage, Training Center completion, open issues, owner pulls, unanswered Ask Rivet questions, and team readiness.",
    forecastTitle: "Day-by-day forecast",
    fixesHeadline: (count: number, gainLabel: string) =>
      `Fix these ${count} items to gain ${gainLabel}`,
    detailedTimeline: "Detailed timeline",
    likelyBreakdown: "Likely breakdown",
    simulationMeta: (totalDays: number, capacityDays: number, firstBreakdownDay: number) =>
      `${totalDays} days modeled · capacity ~${capacityDays} days · first breakdown day ${firstBreakdownDay}`,
  },

  highFriction: {
    metadataTitle: "High friction alerts",
    metadataDescription:
      "Repeat Ask Rivet questions, owner pulls, quiz misses, and plays that get opened but do not stick in training.",
    eyebrow: "Where the floor gets stuck",
    pageTitle: "High friction alerts",
    pageDescription:
      "Rivet surfaces repeat confusion before it becomes another owner pull—each alert recommends a concrete fix.",
    title: "High friction alerts",
    lead: "Same question twice is a signal—not noise. Fix the play, training, or answer before it routes back to you.",
    empty: "No friction patterns crossed thresholds yet. Keep logging pulls and Ask Rivet questions.",
    setupRequired: "Link a workspace to see high friction alerts.",
    viewAll: "View all alerts",
    recommendationsTitle: "Recommended fixes",
    sourceAsk: "Ask Rivet repeat",
    sourceInterruption: "Owner pull repeat",
    sourceQuiz: "Quiz miss pattern",
    sourceViews: "Views vs training",
  },

  universalSearch: {
    placeholder: "Search plays, training, media, people…",
    placeholderCompact: "Search everything…",
    queryTooShort: "Type at least 2 characters to search.",
    searching: "Searching workspace…",
    noResults: "No matches. Try different words or ask Rivet below.",
    viewAll: "View all results",
    askRivetCta: "Ask Rivet this question",
    groupPlays: "Plays",
    groupTraining: "Training",
    groupVideos: "Videos",
    groupPhotos: "Photos",
    groupAskRivet: "Ask Rivet answers",
    groupEmployees: "Employees",
    groupCertifications: "Certifications",
    pageTitle: "Search",
    pageDescription: "Find plays, training modules, media, past Ask Rivet answers, team members, and certifications in one place.",
  },

  askRivet: {
    eyebrow: "Operational memory",
    title: "Ask Rivet",
    lead: "Ask how work runs. Rivet searches plays, training, photos, video, PDFs, FAQs, owner notes, and certifications—then answers in seconds.",
    placeholder: "How do I load the freezer? Who signs off on close?",
    placeholderCompact: "Ask Rivet…",
    submit: "Get answer",
    errorShort: "Ask a full question — Rivet searches your operating memory.",
    lowConfidenceTitle: "No verified standard",
    lowConfidenceAnswer: "I don't have a verified standard for that yet.",
    createPlayCta: "Create a Play",
    sourcesSearchedLabel: "Searched",
    confidenceHigh: "Verified answer",
    confidenceMedium: "Partial match",
    confidenceLow: "No verified play",
    confidenceScoreLabel: "Confidence",
    sourcePlayLabel: "Source play",
    sourceTrainingLabel: "Source training",
    noLinkedTraining: "No training module linked yet",
    verifiedAnswerNote: "Answer pulled verbatim from your operating memory—never invented.",
    reviewTitle: "Review staff answers",
    reviewLead:
      "Approve verified answers or improve them—improvements save as play FAQs for future asks.",
    reviewEmpty: "No answers waiting for review. Medium-confidence answers appear here for a quick owner check.",
    reviewApprove: "Approve",
    reviewImprove: "Improve answer",
    reviewSaveImprovement: "Save & add to play FAQ",
    reviewImprovePlaceholder: "Write the verified answer crew should see…",
    reviewStatusPending: "Needs review",
    reviewStatusImproved: "Improved — pending re-check",
    sourceLinksTitle: "Sources",
    questionsPreventedTitle: "Questions prevented",
    questionsPreventedPageTitle: "Questions prevented",
    questionsPreventedPageDesc:
      "Measurable reduction in owner dependency—what staff asked Rivet, what repeated, and how much owner time stayed on the floor.",
    questionsPreventedIntelLead:
      "When crew gets a verified answer from Ask Rivet instead of texting you, it counts here. Hours saved assume about four minutes per avoided pull.",
    questionsPreventedEmpty:
      "Crew has not asked Rivet yet. Publish plays with success and failure examples—then watch owner pulls drop.",
    heroPreventedLabel: "Questions prevented this month",
    heroHoursLabel: "Estimated owner hours returned",
    heroHoursSub: (avoided: number) =>
      `${avoided} owner pull${avoided === 1 ? "" : "s"} avoided · based on Ask Rivet answers`,
    questionsAnsweredWeek: "Answered this week",
    questionsAnsweredMonth: "Answered this month",
    questionsPreventedMonth: "Prevented this month",
    interruptionsAvoided: "Owner pulls avoided",
    ownerHoursReturned: "Owner hours returned",
    topStaffQuestionsTitle: "Most common staff questions",
    topStaffQuestionsLead: "What the floor asked most often this month—answered in Rivet instead of routing to you.",
    staffQuestionStats: (asked: number, prevented: number) =>
      `${asked} asked · ${prevented} kept off your phone`,
    confusionAreasTitle: "Repeated confusion areas",
    confusionAreasLead:
      "Questions that repeat or lack a verified play—fix these before they become owner interruptions.",
    confusionAreaStats: (asked: number, unverified: number) =>
      `${asked} asks · ${unverified} without verified answer`,
    suggestedFixesTitle: "Suggested fixes",
    suggestedFixesLead: "Prioritized from Ask Rivet patterns—plays, training, or media to close the gap.",
    viewFullIntelligence: "Full questions prevented report",
    mostAskedLabel: "Most asked",
    unverifiedTitle: "No verified answer yet",
    repeatedFixesTitle: "Repeated questions — suggested fixes",
    fixCreatePlay: "Create play",
    fixImprovePlay: "Improve existing play",
    fixAddTraining: "Add training module",
    fixAddMedia: "Add photos/videos",
    fixAskedTimes: (count: number) => `Asked ${count} times`,
    dashboardOpen: "Open Ask Rivet",
    intelligenceEyebrow: "Operating memory",
    intelligenceTitle: "Ask Rivet intelligence",
    intelligenceLead:
      "What the floor asked, what repeated, what lacked a verified play, and how much owner time stayed off your phone this month.",
    intelligencePeriod: "This month (UTC)",
    metricQuestionsAsked: "Questions asked",
    metricRepeated: "Repeated questions",
    metricLowConfidence: "Unanswered",
    metricUnanswered: "Unanswered questions",
    metricPrevented: "Questions prevented",
    metricTimeSaved: "Est. owner time saved",
    repeatedSectionTitle: "Repeated questions",
    repeatedSectionLead: "Same question twice is a signal—fix the play, training, or answer before it routes back to you.",
    lowConfidenceSectionTitle: "Low confidence answers",
    lowConfidenceSectionLead: "Staff asked but operating memory could not verify a play—capture or improve before it becomes an owner pull.",
    recommendationsTitle: "Recommended fixes",
    recommendationsLead: "Prioritized actions from Ask Rivet patterns—not generic advice.",
    recommendationReason: {
      create_play: "No verified play—staff keep asking",
      improve_play: "Play exists but the answer is not sticking",
      add_training: "Wire this play into the Training Center",
      add_media: "Add photos or videos so the answer holds on the floor",
    },
    emptyIntelligence:
      "No Ask Rivet questions logged this month. When staff start asking, this dashboard tracks repeats, gaps, and owner time saved.",
  },

  completionProof: {
    requirementsHeading: "Completion proof required",
    requireChecklist: "Checklist completion",
    requirePhoto: "Photo proof",
    requireVideo: "Video proof",
    requireManagerSignoff: "Manager sign-off",
    proofPhoto: "Photo proof",
    proofVideo: "Video proof",
    proofChecklist: "Checklist",
    proofSignoff: "Manager sign-off",
    uploadPhoto: "Upload photo",
    uploadVideo: "Upload video",
    awaitingSignoff: "Awaiting manager sign-off",
    signoffStep: "Sign off step",
    signoffDone: "Signed off",
    allProofComplete: "Proof complete",
    uploadFailed: "Upload failed — check your connection and try again.",
    signoffStaffHint: "Your manager will sign off in the owner app. You can keep working on other steps while you wait.",
    proofsLocked: "Proof locked after play completion.",
  },

  placeholders: {
    teamRouteTitle: "Backup on the floor",
    teamRoutePurpose:
      "One read on who can cover peaks, where Training Center is thin, and when call-outs still hunt you—once roster depth is enabled for this workspace.",
    teamRouteBody:
      "This route is staged behind a feature flag. Your training data is still live in Training Center—use that until the roster-wide view ships here.",
    teamRoutePrimary: "Training Center",
    coachRouteTitle: "Outside read",
    coachRoutePurpose:
      "A structured brief from plays, Training Center, shifts, and open issues—optional signal, not a second dashboard.",
    coachRouteBody:
      "Outside read is disabled for this deployment. Rivet Index, execution proof, and bottlenecks stay on the main navigation.",
    coachRoutePrimary: "Workspace & account",
  },
} as const
