/**
 * Rivet product copy — plain owner language. Prefer importing from here over scattering UI strings.
 */

export const COPY = {
  connect: {
    title: "Link your business first",
    description:
      "Rivet needs a real workspace to attach to—otherwise there is no floor to read, no shifts to prove, and no bottlenecks to clear off your phone.",
    cta: "Open settings",
  },

  billing: {
    checkoutCanceledTitle: "Checkout was closed",
    checkoutCanceledBody: "Stripe did not charge your card. When you are ready, continue below to try again.",
  },

  setup: {
    eyebrow: "Step 1 · Workspace",
    title: "Name the operation Rivet will track",
    lead:
      "Name your business first—next you pick your type and Rivet installs five SOPs, three training modules, and starter workflows so nothing is empty.",
    cardTitle: "Workspace",
    cardDescription:
      "This record is what standards, training, and proof attach to. You can refine the name later in Settings.",
    nameLabel: "Business name",
    namePlaceholder: "e.g. Northside Cafe",
    industryLabel: "How do you mainly run?",
    footerHint: "Next: pick a business type—we install SOPs, training, and workflows automatically.",
    footerHintBeforeCheckout:
      "Next: complete checkout to unlock Rivet, then pick your business type.",
    submit: "Continue",
    submitting: "Creating workspace…",
  },

  routeRecovery: {
    backOverview: "Back to Overview",
    segmentErrorTitle: "This view did not load",
    segmentErrorBody:
      "Your account is still signed in. You can retry, open Settings if you were linking a workspace, or return to Overview.",
    tryAgain: "Try again",
    openSettings: "Open settings",
    notFoundTitle: "That screen is not in Rivet",
    notFoundBody:
      "The address may be wrong or the page may have moved. Use the sidebar, or go back to Overview or Settings.",
    notFoundOverview: "Go to Overview",
    notFoundSettings: "Open settings",
  },

  settingsWorkspace: {
    title: "Workspace",
    description:
      "Create the business record Rivet uses in Supabase. Until it exists, export and most modules stay empty on purpose—there is no operation to attach to yet.",
    nameLabel: "Business name",
    namePlaceholder: "e.g. Northside Cafe",
    nameHelper: "This is the label Rivet shows for your operation. You can change it later in Supabase if needed.",
    submit: "Create workspace",
    working: "Creating…",
    linkedTitle: "Workspace linked",
    linkedLead: "Rivet is using",
    linkedTrail: " for standards, shifts, and scores.",
    linkedHint: "Invited staff still need profile rows tied to this business; membership tooling is separate.",
    serverSessionRequired:
      "Rivet could not read an authenticated Supabase session for this request. Sign in again, then retry.",
    serverSessionRequiredBypass:
      "Dev mode could not save your workspace. Restart the dev server and try again, or add Supabase keys to .env.local for real persistence.",
    signInToContinue: "Go to sign in",
  },

  shell: {
    tagline: "From “it runs on you” to “it holds without you in every thread.”",
    signedIn: "Signed in",
    accountMenu: "Account menu",
    openMenu: "Open menu",
    navigation: "Navigation",
    settings: "Settings",
    signOut: "Sign out",
  },

  nav: {
    overview: "Overview",
    proofOfTransfer: "Execution proof",
    realityCheck: "Reality check",
    standards: "How the business runs",
    standardsCapture: "Capture a standard",
    training: "Who can carry what",
    shifts: "Can the shift run clean?",
    team: "Backup on the floor",
    bottlenecks: "Things still chasing you",
    interruptions: "Where the business still owns you",
    escapePlan: "Path off your plate",
    settings: "Settings",
    accountSection: "Account",
  },

  hero: {
    eyebrow: "Overview",
    preview: "Preview",
    relianceSub: "Higher = more still depends on you.",
    autonomyLabel: "Escape readiness",
    weekLabel: "Where the business still owns you",
    weekHint: "Logged this week",
    weekHoursLeak: (hours: number) => `≈ ${hours} h of your time`,
    verdictQuestion: "Can the business run without you today?",
    trendLabel: "Escape readiness (7 days)",
    trendHint: "Higher bars = easier week without you",
    trendEmpty: "No history yet.",
    bands: {
      critical: "Very high load on you",
      fragile: "High load on you",
      improving: "Getting better",
      stable: "Mostly OK",
      transferable: "Low load on you",
    },
    notScoredBadge: "Not scored yet",
    rivetEmptyPrimary: "—",
    rivetEmptySub: "Add procedures, training, or a reality check to see your Rivet Score.",
  },

  dashboard: {
    postCheckoutTitle: "Payment received",
    postCheckoutBody:
      "Stripe confirmed checkout. If anything still looks locked, wait a few seconds for your workspace to update, then refresh this page.",
    postCheckoutDismiss: "Dismiss",
    loadErrorTitle: "Overview could not load",
    loadErrorBody:
      "Your session is unchanged. Retry once—if this keeps happening, open Settings or sign out and back in while we check connectivity.",
    criticalHeading: "Needs your attention",
    criticalAllLink: "See all open issues",
    criticalEmpty: "Nothing urgent flagged right now.",
    badgeBottleneck: "Still chasing you",
    badgeStandard: "Standard",
    badgeRisk: "Risk",
    badgeTraining: "Training",
    badgeGap: "Thin write-up",
    statusOpen: "Open",
    statusProgress: "In motion",
    nextEyebrow: "Do this next",
    proofHeading: "Execution proof",
    proofFullLink: "See full proof",
    proofEmpty:
      "No completed checklist runs on record yet—finish opening or closing on the floor, then refresh.",
    proofWin: "Off your plate",
    teamHeading: "Who can carry the floor",
    teamLink: "Open teaching",
    teamTrainingDone: "Modules finished",
    teamReadinessAvg: "Floor coverage",
    teamSignals: "What the score sees",
    teamSignalTeam: "People depth",
    teamSignalTrain: "Teaching depth",
    depthHeading: "Rivet Score breakdown",
    depthExpand: "See what drives your score",
    depthExpandHint: "optional detail",
    depthHeatHint: "Darker = more still depends on you in that area.",
    warningsHeading: "Heads up",
    metrics: {
      standards: "Procedures written",
      training: "Training done",
      bottlenecks: "Open issues",
      onYou: "Waiting on you",
    },
    pulseHeading: "At a glance",
    pulse: {
      ownerInterruptions: "Routed back to you this week",
      proceduresMissing: "Procedures missing",
      trainingCompletion: "Training completion",
      issuesUnresolved: "Unresolved issues",
      escapeReadiness: "Escape readiness",
      rivetScore: "Rivet Score",
    },
    pulseRivetHint: "Higher = more depends on you",
    pulseEscapeHint: "Higher = more likely five days away holds",
    biggestRisksTitle: "Biggest Risks This Week",
    biggestRisksSubtitle:
      "Ranked from dependency score, missing documentation, training completion, and what still routes back to you.",
    metricNoData: "No data yet",
    scoreInsufficientFounderLabel: "Not scored yet — add procedures, training, or issues to calculate.",
    scoreInsufficientRiskCaption:
      "Add a few procedures, training modules, or logged pulls on you so Rivet can score your business.",
    executionProofEmpty:
      "No completed checklist runs on record yet—finish a daily run on the floor so execution shows up here.",
    executionProofRun: "Completed run",
    teamSignalsEmpty:
      "Category scores need training assignments or readiness rows to describe people and teaching depth.",
    marketingDemoCaption: "Illustrative preview only—your live overview uses your workspace, not made-up numbers.",
    setupGateTitle: "Link your business to load this overview",
    setupGateBody:
      "Scores, heatmaps, and proof pull from your workspace on the record. Until then, nothing here is estimated—we leave the numbers blank on purpose.",
    setupGateCta: "Open settings",
    setupGateSecondary: "Reality check",
    setupGateFootnote:
      "The full overview—including transfer signals drawn from your workspace—loads after you link a business in Settings.",
    setupScoreMessage:
      "Your Rivet Score appears after you link a business. We do not make up numbers for an empty workspace.",
    setupCategoryHint: "Fills in once the workspace is linked.",
    setupFounderLabel: "Not measured without a linked business.",
    setupRiskCaption: "No floor read yet.",
    setupNextTitle: "Link your business",
    setupNextDesc: "Name the operation in Settings so this overview can attach to real shifts, plays, and people.",
    setupNextCta: "Open settings",
    coldStartTitle: "Workspace is linked—next, put a few facts on the record",
    coldStartBody:
      "Rivet reads from standards, teaching, shifts, and bottlenecks. With nothing logged yet, the index is only directional. Add one active standard or run a short reality check so the dashboard reflects your real floor.",
    coldStartCtaStandards: "Browse standard templates",
    coldStartCtaReality: "Run reality check",
    premiumSetupEyebrow: "Welcome to Rivet",
    premiumSetupTitle: "Finish workspace setup to open the Overview",
    premiumSetupBody:
      "The Overview reads from a real business record—standards, shifts, teaching, and proof. Start the guided setup to name your operation and choose how you run, then complete the Reality Check.",
    premiumSetupCta: "Start guided setup",
    firstStandardTitle: "Capture your first standard",
    firstStandardBody:
      "Your Reality Check is on file, but nothing is written to the floor yet. One short capture turns tribal knowledge into something the team can run without texting you.",
    firstStandardCta: "Capture a standard",
    errorNextTitle: "Could not load overview",
    errorNextDesc:
      "Something interrupted the data load. Your workspace is still safe—this is usually temporary. Try reloading, or open Settings if you were changing workspace details.",
    errorNextCta: "Try again",
    teamLinkTraining: "Open teaching",
  },

  counters: {
    bottlenecks: "Open messes",
    weekInterrupts: "Routed to you this week",
    needsYou: "Waiting on you",
    trainingDone: "Modules done",
    standardDepth: "Plays fleshed out",
    standardsGapBadge: "Thin plays",
    standardsGapText:
      "Some plays still read too thin to hand off—tighten cash, open/close, and one quality spine first.",
    standardsGapLink: "Open plays",
  },

  heatmap: {
    title: "Score by area",
    subtitle: "Darker = more still depends on you in that area.",
  },

  issues: {
    metadataTitle: "Things still chasing you",
    eyebrow: "Off your texts",
    title: "Things still chasing you",
    description:
      "Problems repeated enough times that they deserve a system—not another text message.",
    logCta: "+ Quick capture",
    tabsAll: "Everything",
    tabsYou: "Needs you",
    tabsOpen: "Not cleared",
    tabsCleared: "Cleared",
    tabsAria: "Things still chasing you filters",
    backToAll: "Things still chasing you",
    detailFallbackTitle: "Things still chasing you",
    saveCta: "Save",
    emptyDescription:
      "Either the queue is clear or filters are hiding rows. When something blocks the standard, log it here so the fix lives in the business—not in your texts.",
    emptyFilterTitle: "Nothing in this view.",
    starterEyebrow: "Examples",
    starterTitle: "What shows up here",
    starterLead: "Repeated problems get named once—then the team fixes the system, not your inbox.",
    starterExampleBadge: "Example",
    logFirstIssueCta: "+ Quick capture",
    painScoreLabel: "Pain score",
    painScoreHint: "0–100 from frequency, time cost, owner involvement, and recency.",
    painScorePreviewLabel: "Pain score preview",
    painScorePreviewHint: "Updates as you set severity and owner involvement.",
    painScoreDriverFrequency: "Frequency",
    painScoreDriverTimeCost: "Time cost",
    painScoreDriverOwner: "Owner involvement",
    painScoreDriverRecency: "Recency",
    painScoreFrequencyOnce: "First time logged with this title.",
    painScoreFrequencyRepeat: (count: number) => `${count} times in the last 30 days.`,
    painScoreTimeCostDetail: (severity: string) => `Severity: ${severity}.`,
    painScoreOwnerRequired: "Owner must decide before the team moves.",
    painScoreOwnerOptional: "Team can likely clear without owner.",
    painScoreRecencyDetail: (days: number) =>
      days <= 1 ? "Logged in the last day." : `${days} day(s) since logged.`,
    costEstimateTitle: "Estimated cost",
    costEstimateHint:
      "Modeled from severity, category, repeat frequency, and owner load—so you see money, not just noise.",
    costEstimateMonthlyLabel: "Monthly projection",
    costEstimateMonthlyShort: "Est.",
    costEstimateLabor: "Labor impact",
    costEstimateLostSales: "Lost sales",
    costEstimateOwnerTime: "Owner time",
    costEstimateLaborDetail: (minutes: number, hourly: number) =>
      `~${minutes} min team time per incident @ $${hourly}/hr.`,
    costEstimateLostSalesDetail: "Category + severity modeled refund, remake, and walk-away risk.",
    costEstimateOwnerDetail: (minutes: number, hourly: number) =>
      minutes > 0
        ? `~${minutes} min owner attention per incident @ $${hourly}/hr.`
        : "No owner minutes while resolved.",
    costEstimateIncidentsOnce: "Priced as 1 incident in the last 30 days.",
    costEstimateIncidentsRepeat: (count: number) =>
      `Priced at ${count} incidents in the last 30 days—repeats multiply the bleed.`,
    costEstimateResolvedNote: "Resolved—projection shows residual tail only; ongoing bleed stops.",
    costEstimateDisclaimer:
      "Estimates use default wage assumptions ($22/hr team, $85/hr owner opportunity). Adjust when you wire real payroll.",
    costEstimateListBleedLabel: "Unresolved issues — estimated monthly bleed",
    costEstimateListBleedHint: "Sum of modeled labor, lost sales, and owner time across open issues.",
    fixRecommendationTitle: "Recommended fix",
    fixRecommendationLead: "This issue repeated—Rivet mapped a play, training, and who should own the fix.",
    fixRecommendationRootCause: "Why it keeps coming back",
    fixRecommendationSuggestedPlay: "Suggested play",
    fixRecommendationSuggestedTraining: "Suggested training",
    fixRecommendationSuggestedOwner: "Suggested owner",
    fixRecommendationRepeatReduction: "Estimated reduction in repeats",
    fixRecommendationRepeatReductionValue: (percent: number) => `≈ ${percent}%`,
    fixRecommendationRepeatReductionHint: (count: number) =>
      `Based on ${count} logs in 30 days plus severity and owner load.`,
    fixRecommendationNone: "None matched yet",
    fixRecommendationRelatedExisting: (title: string) => `Related existing: ${title}`,
    fixRecommendationCreateCta: "Create fix",
    fixRecommendationCreating: "Creating draft…",
    fixRecommendationRepeatBadge: "Repeat · fix ready",
    hauntingWeekTitle: "Haunting this week",
    hauntingWeekHint: "Issues logged since Monday UTC—ranked by what keeps pulling you back.",
    hauntingWeekSortAria: "Sort haunting issues",
    hauntingWeekSortFrequency: "Frequency",
    hauntingWeekSortImpact: "Estimated impact",
    hauntingWeekSortTimeCost: "Time cost",
    hauntingWeekEmpty: "Nothing logged this week yet.",
    hauntingWeekFrequencyLabel: "Frequency",
    hauntingWeekImpactLabel: "Impact",
    hauntingWeekTimeCostLabel: "Time cost",
    hauntingWeekImpactShort: (score: number) => `Impact ${score}`,
    hauntingWeekNeedsYou: "Needs you",
    issueOwnerLabel: "Owner",
    issueOwnerPlaceholder: "Assign owner",
    issueOwnerUnassigned: "Unassigned",
    issueDueDateLabel: "Due date",
    issueStatusLabel: "Status",
    issueTitleLabel: "Title",
    issueTitlePlaceholder: "Short summary",
    issueDescriptionLabel: "Description",
    issueDescriptionPlaceholder: "What happened, what you tried, what you need next",
    issueCategoryLabel: "Category",
    issueSeverityLabel: "Severity",
    issueOwnerRequiredHint: "This needs you—the owner—to decide or act before the team can move on.",
    issueOwnerRequiredOverviewHint: "Only you can unblock (shows on Overview)",
    issueSaving: "Saving…",
    issueSaved: "Saved.",
    issueSaveChanges: "Save changes",
    issueReportedAt: "Reported",
    issueLinksTitle: "Linked items",
    issueLinksHint: "Connect this issue to the SOP, training, owner pull, or person it touches.",
    issueLinksEmpty: "Nothing linked yet—add context so the team knows where to look.",
    issueLinksAddKind: "Link type",
    issueLinksAddTarget: "Pick item",
    issueLinksAddTargetPlaceholder: "Choose…",
    issueLinksAddCta: "Add link",
    issueLinksAdding: "Adding…",
    issueLinksRemoveAria: (title: string) => `Remove link to ${title}`,
    quickCaptureCta: "+ Quick capture",
    quickCaptureTitle: "Quick capture",
    quickCaptureHint: "Save in under 10 seconds—add detail later if needed.",
    quickCaptureWhatHappened: "What happened?",
    quickCaptureWhatPlaceholder: "One line is enough—e.g. cooler alarm, remake queue, scheduling gap",
    quickCapturePeople: "People involved",
    quickCapturePeopleEmpty: "No team roster yet—capture names in the note for now.",
    quickCaptureTimeLost: "Time lost",
    quickCaptureVoiceNote: "Voice note",
    quickCaptureVoiceStop: "Stop recording",
    quickCaptureVoiceTranscribing: "Transcribing…",
    quickCaptureSave: "Save",
    quickCaptureSaving: "Saving…",
    lifecycleTitle: "Issue lifecycle",
    lifecycleHint: "From first log through fix, training, and dependency relief.",
    lifecycleStageLogged: "Issue logged",
    lifecycleStagePattern: "Pattern detected",
    lifecycleStageFix: "Suggested fix created",
    lifecycleStageTraining: "Training assigned",
    lifecycleStageProgress: "Progress tracked",
    lifecycleStageDependency: "Dependency score updated",
    lifecycleDetailLogged: "Captured and on the board.",
    lifecycleDetailPattern: (count: number) => `${count} repeat(s) in 30 days—system fix warranted.`,
    lifecycleDetailFix: "Play or training module linked to this issue.",
    lifecycleDetailTraining: (count: number) =>
      count === 1 ? "1 team member assigned." : `${count} team members assigned.`,
    lifecycleDetailProgress: "Status moved or training underway.",
    lifecycleDetailDependency: (score: number) => `Handoff score refreshed at ${score}.`,
    lifecycleAssignTrainingCta: "Assign suggested training",
    lifecycleAssigningTraining: "Assigning…",
    shiftSectionTitle: "Things still chasing you from this shift",
    shiftReportHint: "Opens Things still chasing you and is linked to this shift when you are in a run.",
    newMetadataTitle: "Full issue form",
    newEyebrow: "Off your texts",
    newTitle: "Full issue form",
    newDescription: "Put the block on paper before it becomes a 9pm text chain.",
    newConnectDesc: "Link your business first—then this saves to your floor.",
    newSuccessDescription:
      "Anyone on the team can record what is stuck. Flag when only you can move it—that keeps owner load visible instead of invisible.",
  },

  interruptions: {
    featureTitle: "Where the business still owns you",
    featureDescription:
      "Every approval, question, and decision routed back to you reveals where the system is unfinished.",
    metadataTitle: "Where the business still owns you",
    eyebrow: "Operational dependence",
    title: "Where the business still owns you",
    description:
      "Every approval, question, and decision routed back to you reveals where the system is unfinished.",
    noBizEyebrow: "Owner pulls",
    noBizTitle: "Where the business still owns you",
    noBizDesc:
      "Link the workspace first—then the team can log approvals, questions, and decisions that still route back to you.",
    logEyebrow: "Fast log",
    logTitle: "Log an interruption",
    logDescription: "Two taps: what kind of pull, how long it burned, one honest line. Done.",
    logSaved: "Saved. It shows on the dashboard immediately.",
    dashboardCta: "Open dashboard",
    logCta: "Log another",
    weekStat: "This week (UTC Mon–Sun)",
    hoursLeak: "Estimated owner time",
    hoursLeakHint: "Sum of time estimates your team logged—rough, but directionally honest.",
    trendTitle: "14-day heat map",
    trendHint: "Each cell is one UTC day. Darker means more owner time lost—hover for details.",
    heatmapLegendLabel: "Intensity",
    heatmapInterruptionsLabel: "Interruptions",
    heatmapTimeLostLabel: "Time lost",
    heatmapMostCommonIssueLabel: "Most common issue",
    heatmapNoCommonIssue: "None logged",
    kindsTitle: "What kind of pull",
    kindsHint: "Where decisions collapse back to you.",
    topLeaksTitle: "Top Leaks",
    topLeaksHint: "Repeat pulls ranked by owner time—and what to write down to stop them.",
    topLeakOccurrencesLabel: "Occurrences",
    topLeakOwnerTimeLabel: "Estimated owner time",
    topLeakSuggestedFixLabel: "Suggested fix",
    rolesTitle: "Most dependent roles",
    rolesHint: "Grouped by the role on the roster card—coarse, but it surfaces who’s stuck in your pocket.",
    peopleTitle: "Who logged the most",
    peopleHint: "Usually the people closest to the fire. Pair with teaching and written plays.",
    recentTitle: "Latest on the record",
    recentHint: "Newest first. Names come from the team roster.",
    emptyTrend: "No interruptions logged in this window yet—when they start, the shape shows up here.",
    emptyTopLeaks: "No repeat leaks yet—when the same label shows up twice, it ranks here.",
    emptyRepeats: "No repeat leaks yet—when the same label shows up twice, it ranks here.",
    emptyRoles: "No role signal yet.",
    starterEyebrow: "Examples",
    starterTitle: "What gets logged here",
    starterLead:
      "These are the pulls that usually land on the owner—approvals, questions, judgment calls, and escalations.",
    starterExampleBadge: "Example",
    logFirstPullCta: "Log first pull",
    starterSectionHint: "Log your first pull to see live data here.",
    actionHint: "Log pulls in the moment—before memory rounds the edges.",
    minutesLabel: "Minutes on you",
    summaryLabel: "One-line label",
    summaryPlaceholder: "e.g. “Approve comp for call-out” or “Guest wants exception to policy”",
    detailLabel: "Optional context",
    detailPlaceholder: "What was tried, what was blocked—only if it helps the next fix.",
    kindLabel: "Type",
    urgencyLabel: "How urgent",
    sourceLabel: "How it reached you",
    channelTitle: "Channel breakdown",
    channelHint: "Where pulls find you—text, call, floor tap, Slack, email, or other.",
    severityTitle: "Pull severity",
    severityHint: "Estimated from time spent, urgency, and how often the same pull repeats in 14 days.",
    severityPreviewLabel: "Estimated severity",
    severityPreviewHint: "Uses time and urgency now. Repeat pulls raise severity once similar labels show up.",
    actionPlanTitle: "Recommended fix",
    actionPlanLead: "Rivet mapped this pull to a draft play, related docs, and who it affects.",
    actionPlanRelatedSop: "Related SOP",
    actionPlanRelatedModule: "Training module",
    actionPlanNoneFound: "None matched yet",
    actionPlanPeopleAffected: "People affected",
    actionPlanNoPeople: "No roster matches yet.",
    actionPlanDraftFix: "Draft fix",
    actionPlanEditDraft: "Review draft",
    actionPlanApprove: "Approve fix plan",
    actionPlanPublish: "Publish fix",
    actionPlanDismiss: "Dismiss",
    actionPlanOwnerOnlyHint: "Only the owner can approve and publish fixes.",
    actionPlanGenerating: "Building your fix plan…",
    actionPlanStatusDraft: "Draft",
    actionPlanStatusApproved: "Approved",
    actionPlanStatusPublished: "Published",
    actionPlanStatusDismissed: "Dismissed",
    submit: "Log it",
    submitting: "Saving…",
    dashboardStripCta: "Open the leak map",
    dashboardStripLoggedSuffix: "logged this week",
    unitPulls: "pulls",
    fixSuggestionsTitle: "Recommended fixes",
    fixSuggestionsLead:
      "Repeat leaks mapped to root causes—Rivet estimates what a written play or module could recover.",
    fixSuggestionBadge: "Recommended fix",
    fixSuggestionRootCause: "Root cause",
    fixSuggestionSuggestedFix: "Suggested fix",
    fixSuggestionSop: "SOP",
    fixSuggestionTrainingModule: "Training module",
    fixSuggestionInterruptionsLabel: "Est. interruptions prevented / mo",
    fixSuggestionTimeLabel: "Est. owner time recovered / mo",
    fixSuggestionCreatePlay: "Create play",
    fixSuggestionCreateModule: "Create module",
    valueMetricsTitle: "Owner value",
    valueMetricsLead:
      "Time and money the business gets back when pulls stop routing to you—based on this week’s trend and recommended fixes.",
    valueMetricsHoursLabel: "Hours returned this week",
    valueMetricsBusinessLabel: "Estimated business value",
    valueMetricsBusinessHint: "Based on your hourly value × hours returned",
    valueMetricsBusinessEmpty: "Set your hourly value below to see dollar impact.",
    valueMetricsHourlyLabel: "Your hourly value (CAD)",
    valueMetricsHourlyPlaceholder: "e.g. 75",
    valueMetricsSaveHourly: "Save hourly value",
    valueMetricsSaving: "Saving…",
    valueMetricsHourlyInvalid: "Enter a valid hourly value (0 or greater).",
    valueMetricsSourceActual: "Fewer pulls logged than last week—actual time returned.",
    valueMetricsSourceProjected: "Projected from recommended fixes if you ship them this week.",
    valueMetricsSourceNone: "Log repeats and fixes to see recoverable time.",
  },

  operations: {
    metadataTitle: "Shifts",
    eyebrowOwner: "Proof on the record",
    titleOwner: "Can the shift run clean?",
    descOwner:
      "Opening and closing with the same checklist every time—so the standard held is visible, not something only you remember.",
    eyebrowStaff: "Your shift",
    titleStaff: "Can the shift run clean?",
    descStaff: "Run open and close from your phone. The dated record is what keeps you out of the group chat.",
    noBizEyebrow: "Shift proof",
    noBizTitle: "Can the shift run clean?",
    noBizDesc: "When the business is linked, this is where today’s open and close live—with receipts.",
    floorLabel: "Today’s checklists",
  },

  training: {
    metadataTitle: "Who can carry what",
    noBizEyebrow: "Teaching",
    noBizTitle: "Who can carry what",
    noBizDesc: "Modules tied to how you actually run—so “trained” means something on the floor, not a checkbox.",
    eyebrow: "Capability",
    title: "Who can carry what",
    description: "Standards linked to people—so opening alone and guest recovery are known quantities, not guesses.",
    newModule: "New module",
    modulesHeading: "Modules",
    emptyTitle: "No modules yet",
    emptyDesc: "Start where you get interrupted most—open, cash, or guest recovery—and wire the plays people should run.",
    emptyCta: "First module",
    exampleEyebrow: "When modules exist",
    exampleDesc: "Progress and readiness pull from the same standards your team already has to hit.",
    teamSectionTitle: "People on the business",
    teamSectionLead:
      "Each card shows modules, play completion, and a calculated readiness score with manager overrides when you have seen something different on the floor.",
    teamEmpty: "No people on this workspace yet—when teammates have accounts, link them to this business from Settings.",
    teamLink: "Open settings",
    employeeCardReadiness: "Readiness score",
    employeeDelegationHeading: "Floor readiness",
    employeeDelegationHint:
      "Calculated from SOP completion, quizzes, videos, manager observations, sign-offs, and certifications. Override any line if you have seen something different on the floor.",
    employeeModulesHeading: "Modules on them",
    employeeNoModules: "No modules on them yet.",
    employeeDonePlays: (n: number) => `Hit (${n})`,
    employeeRemainingPlays: (n: number) => `Still open (${n})`,
    employeeAddModule: "Add module",
    employeeChooseModule: "Choose a module…",
    employeeAssign: "Assign",
    employeeRemove: "Remove",
    employeeRemoveConfirm: (title: string) => `Pull “${title}” off this person?`,
    employeeSopFootnote: "Checking plays updates the module status automatically.",
    matrixLink: "Team readiness matrix",
  },

  managerObservations: {
    timelineTitle: "Manager observations",
    timelineLead:
      "Floor notes from you—positive wins, coaching moments, and critical issues. These feed the manager observations readiness signal.",
    typeLabel: "Observation type",
    typePositive: "Positive",
    typeImprovement: "Improvement",
    typeCritical: "Critical issue",
    notesLabel: "Notes",
    notesPlaceholder: "What did you see on the floor?",
    submit: "Log observation",
    empty: "No observations logged yet.",
    loggedBy: (name: string) => `Logged by ${name}`,
  },

  readinessMatrix: {
    metadataTitle: "Team readiness matrix",
    eyebrow: "Capability",
    title: "Team readiness matrix",
    description:
      "Skills across your team at a glance—green is certified and floor-ready, yellow is in progress, red is not trained yet.",
    backToTraining: "Back to training",
    moduleRoleFilter: "Filter by module role",
    employeeRoleFilter: "Filter by employee role",
    allEmployeeRoles: "All employee roles",
    moduleColumn: "Module / skill",
    noModules: "Add training modules to see the readiness matrix.",
    noEmployees: "Add team members to see the readiness matrix.",
    cellTitle: (employee: string, module: string, status: string) =>
      `${employee} · ${module}: ${status}`,
  },

  trainingPortal: {
    metadataTitle: "My training",
    homeTitle: "My training",
    homeLead: "Complete assigned modules on your phone—video, checklist, quiz, and photo proof when required.",
    emptyTitle: "No modules assigned yet",
    emptyDesc: "When your manager assigns training or sends an invite link, modules show up here.",
    joinTitle: "Training invite",
    joinLead: "Sign in to start this module. Works best on your phone between shifts.",
    joinSignIn: "Sign in to start",
    joinCreateAccount: "Create account",
    inviteInvalid: "This invite link is invalid or expired. Ask your manager for a new one.",
    inviteWrongAccount: "This invite was sent to someone else. Sign in with the correct account.",
    inviteHeading: "Send to employee",
    inviteHint: "Share by email, SMS, or copy a link. They open the mobile training portal and complete each play.",
    inviteEmployee: "Assign to (optional)",
    inviteAnyone: "Anyone with the link",
    inviteEmail: "Email",
    invitePhone: "Phone (SMS)",
    inviteCopyLink: "Create invite link",
    inviteEmailBtn: "Send email",
    inviteSmsBtn: "Send SMS",
    inviteCopy: "Copy link",
    inviteCopied: "Copied",
    openPortal: "Open training portal",
    portalCtaLead: "Employees complete modules on their phone—video, checklist, quiz, and photos.",
  },

  certifications: {
    profileHeading: "Certifications",
    profileEmpty: "No certifications earned yet.",
    badgeTitle: (label: string, certifiedAt: string) =>
      `${label} · certified ${new Date(certifiedAt).toLocaleDateString(undefined, { dateStyle: "medium" })}`,
    trackerHeading: "Certifications",
    trackerHint:
      "Earned after module completion, all quizzes passed, and your manager sign-off.",
    stepModule: "Module completed",
    stepQuiz: "Quizzes passed",
    stepSignOff: "Manager sign-off",
    signOffButton: "Sign off on floor",
    certifiedLabel: "Certified",
  },

  team: {
    metadataTitle: "Backup on the floor",
    eyebrow: "Depth",
    title: "Backup on the floor",
    description: "Who exists beyond you, what they can run alone, and how teaching lines up—so peak isn’t a solo act.",
    emptyEyebrow: "Roster",
    emptyTitle: "Backup list is still building",
    emptyDesc:
      "Teaching already uses the people on your business. This roster-wide view is next—use Who can carry what for per-person cards today.",
    stubNote:
      "No fabricated roster cards here. When this page ships, it will pull the same real readiness data you already see under Teaching.",
    emptyTraining: "Open teaching",
    emptySettings: "Business settings",
  },

  sops: {
    metadataTitle: "How the business runs",
    eyebrow: "The real bar",
    title: "How the business runs",
    descNoBiz: "The plays someone can run without interpreting you—short enough to use on a hot line.",
    desc: "Runnable plays in plain language. When the bar is explicit, fewer decisions boomerang to you.",
    starterTitle: "Starter plays",
    starterBody: "Drop in open, close, bar, bakery, or cash drafts—then tune for your gear, vendors, and house rules.",
    starterCta: "Open gallery",
    gallery: "Starter gallery",
    capture: "Capture a play",
    new: "New play",
    emptyEyebrow: "First play",
    emptyTitle: "Start with what only you still run.",
    emptyDesc: "Pick the question your team asks you most—or grab a draft from the gallery and edit it to your line.",
    browseGallery: "Browse gallery",
    authorScratch: "Write from scratch",
    alertTitle: "No plays yet — you are the system",
    alertBody:
      "Without published plays, teaching has nothing to attach to and shifts have nothing to score. Put open or cash in the library first—then the floor stops improvising under pressure.",
    exampleEyebrow: "When the library has meat",
    exampleDesc: "Audits and opening runs both trace back to the same plays—here is what that looks like filled in.",
    exampleOpeningTitle: "Opening tied to plays (example)",
  },

  templates: {
    metadataTitle: "Starter plays",
    back: "Back to plays",
    title: "Starter plays",
    description: "Industry packs and classics as drafts—tune to your line before anyone runs them under pressure.",
    noBizDesc:
      "Starters land in your play library. Link the operation in Settings, then install drafts in one pass.",
    heroBadge: "Starter gallery",
    heroTitle1: "Packs written for real floors.",
    heroTitle2: "Plus the open, close, cash, and bar starters you already know.",
    heroLead:
      "Each industry ships eight linked drafts—open, close, quality, guest expectations, onboarding, escalation, roles, and a shift checklist. Install one card or the whole pack; everything lands as a draft you own.",
    listEyebrow: "Plays",
    listTitle: "Starter gallery",
    listDesc: "Filter by industry or category. Rename, retune vendors, and check local law before these hit a live line.",
    emptyFilter: "Nothing in this slice.",
    emptyFilterLink: "all starters",
  },

  welcome: {
    dismiss: "Dismiss",
    region: "Welcome",
    onboardingAria: "Welcome strip",
    doneLine: "You already did the honest pass.",
    doneTitle: "The uncomfortable part is on paper—so you can fix it on purpose.",
    doneBody: "Re-open your dependency read when you need a reset, then keep moving load into plays, teaching, and shift proof.",
    reportAgain: "Open report again",
    capture: "Capture a play",
    todoEyebrow: "If you are carrying too much",
    todoTitle: "You are not “bad at delegating.” The work still routes through you.",
    todoBody:
      "Eight blunt questions, one straight read on how fused the operation is to you—no shame, no fluff. Then Rivet helps you move answers into plays your team can run.",
    todoCta: "Five-minute reality check",
    chipSettingsLinked: "Settings",
    chipSettingsUnlinked: "Link business first",
    chipBrowse: "Browse starter plays",
  },

  proofPage: {
    title: "Execution proof",
    lead: "Evidence the operation can carry load without routing every judgment through you—not vibes, what the record shows.",
    backOverview: "Owner overview",
    openStandards: "Open standards",
    unlinkedHeadline: "Execution proof attaches to your business",
    unlinkedLead:
      "Link the operation in Settings. Wins from shifts, teaching depth, and cleared bottlenecks land here as they happen—no demo filler.",
  },

  proofPanel: {
    eyebrow: "Execution proof",
    signalMix: "Signal mix",
    signals: (n: number) => `${n} signals`,
    bucketTransferred: "Off your plate",
    bucketTransferredDesc: "Things the team proved they can carry.",
    bucketFragile: "Still uneven",
    bucketFragileDesc: "Moving, but not trustworthy yet under pressure.",
    bucketOwner: "On you",
    bucketOwnerDesc: "Still concentrated until plays, teaching, or clears happen.",
    bucketStable: "Steadier",
    bucketStableDesc: "Signals holding calmer as you reinforce structure.",
    bucketEmpty: "Nothing here right now.",
    productSurface: "Product surface",
    introTitle: "The same views your team runs",
    introBody:
      "Checklists, audits, teaching depth, dependency—shown as proof, not mockups. Your workspace replaces this with live data.",
    illustrative: "Examples use fixed demo lines—your account shows your business.",
    introReceipts:
      "Each card ties to shift proof, readiness, bottlenecks, or Rivet Index history—not a wish list.",
  },

  coach: {
    unlinkedTitle: "Outside read needs a linked business",
    unlinkedLead:
      "This brief is built only from your workspace signals. Link the operation in Settings, then come back for a grounded read—nothing here is invented.",
    unlinkedCta: "Open settings",
    errorTitle: "Could not load Outside read",
    errorLead: "Try again in a moment. If it keeps failing, refresh the page or check your connection.",
    retryCta: "Try again",
  },

  onboarding: {
    questionProgress: (i: number, n: number) => `Question ${i} of ${n}`,
    introEyebrow: "Reality check",
    reportEyebrow: "Dependency read",
    reportIndexLabel: "How fused you are to the operation",
    reportIndexHint:
      "Higher = more still rides on your judgment, memory, and presence—not because you want it that way, but because the system is not finished yet.",
    breakdownHeading: "Dependency breakdown",
    breakdownSubheading:
      "How each category contributes weighted points to your score. Tackle the highest bar first for the fastest drop.",
    leverageLabel: "Highest leverage action:",
    leverageImprovementPrefix: "Estimated score improvement:",
    leverageCta: "Start this fix",
    bandCritical: "Heavy load",
    bandStrained: "Strained",
    bandContained: "Earlier than it feels",
    interpretationHeading: "Rivet Interpretation",
    interpretationCritical: "Critical dependency",
    interpretationHiddenRisk: "Hidden risk",
    interpretationPredicted: "Predicted outcome",
    interpretationFirstAction: "Suggested first action",
    interpretationActionCta: "Start this fix",
    strengthsHeading: "Strengths detected",
    uncomfortableHeading: "The straight truth",
    stakesHeading: "If nothing changes",
    movesHeading: "Your first moves here",
    movesOpen: "Open →",
    persistIdle: "Saved on this device. Retake anytime.",
    persistSaving: "Saving to your workspace…",
    persistSaved: "Saved into your overview inputs.",
    persistSkipped: "Create your workspace first (Overview → guided setup), then save again to keep this in history.",
    persistError: "Could not save—your read is still here on this device.",
    retake: "Retake",
    backOverview: "Back to overview",
    livePreview: (n: number) => `Live preview index: ${n}/100`,
    begin: "Begin",
    continue: "Continue",
    seeReport: "See read",
    back: "Back",
    reportIntroCard1:
      "Rivet is for owners who are tired of being the glue between what you meant and what happened on the floor.",
    reportIntroCard2: "We will not shame you for working hard. We will map where the load is structurally stuck.",
  },

  readinessQuestions: [
    { field: "open_alone" as const, label: "Can they open alone?" },
    { field: "close_alone" as const, label: "Can they close alone?" },
    { field: "train_others" as const, label: "Can they teach the next person?" },
    { field: "handle_complaints" as const, label: "Can they handle a hard guest without you?" },
  ],

  readinessBadges: {
    not_ready: "Still needs you close",
    learning: "Building",
    ready_with_support: "OK if you are one text away",
    fully_ready: "Can own it",
  },

  ownerWizard: {
    intro: {
      title:
        "If you are wiped and still the answer key, that is not drama—that is the floor telling the truth.",
      lead:
        "Blunt questions, then a straight read of how much still routes through you—and what to bump first so the line can carry more without you as human middleware.",
      speed: "Under five minutes. Answer like nobody is grading you—because nobody is.",
    },
    days: {
      title: "How many days a week does the business own you?",
      subtitle: "Count the days you are mentally on—even when you are not on the line the whole time.",
      choices: [
        { value: "0-2" as const, label: "0–2 days", hint: "Part-time owner or mostly off floor" },
        { value: "3-4" as const, label: "3–4 days", hint: "Heavy week, but not seven-on" },
        { value: "5-6" as const, label: "5–6 days", hint: "The business owns most of your calendar" },
        { value: "7" as const, label: "7 days", hint: "No clean off switch yet" },
      ],
    },
    open: {
      title: "Can someone else open clean without you?",
      subtitle: "Not “they help sometimes”—can the place open right if you do not show?",
      choices: [
        { value: "yes" as const, label: "Yes", hint: "A trained opener can run start to finish" },
        { value: "sometimes" as const, label: "Sometimes", hint: "Holds until an exception hits" },
        { value: "no" as const, label: "No", hint: "It still routes through you" },
      ],
    },
    close: {
      title: "Can someone else close clean without you?",
      subtitle: "Cash, deposits, alarms, temps, cleanup—with you out of the building.",
      choices: [
        { value: "yes" as const, label: "Yes", hint: "A trained closer can finish safely" },
        { value: "sometimes" as const, label: "Sometimes", hint: "Depends on the night" },
        { value: "no" as const, label: "No", hint: "You are still closer of last resort" },
      ],
    },
    interrupts: {
      title: "How often does the team pull you out of flow?",
      subtitle: "Texts, shoulder taps, “quick questions” that break what you were doing.",
      choices: [
        { value: "rarely" as const, label: "Rarely" },
        { value: "weekly" as const, label: "A few times a week" },
        { value: "daily" as const, label: "Most days" },
        { value: "constant" as const, label: "All day", hint: "It barely stops" },
      ],
    },
    breaks: {
      title: "What wobbles first when you step away?",
      subtitle: "One honest sentence. If it is a chain, name the first domino.",
      labelSr: "What wobbles when you step away",
      placeholder:
        "e.g. Line speeds up but quality slips, or cash waits because only I know the vendor workaround.",
      footnote: "Optional—and the read is sharper when you name the crack.",
    },
    timeoff: {
      title: "Have you skipped real time off because the business cannot release you?",
      subtitle: "Not vacation photos—days you could actually go dark.",
      choices: [
        { value: "yes" as const, label: "Yes" },
        { value: "no" as const, label: "No" },
        {
          value: "prefer_not" as const,
          label: "Prefer not to say",
          hint: "We will still generate your read",
        },
      ],
    },
    standards: {
      title: "Are plays on paper—or mostly in your head?",
      subtitle: "What a new hire actually inherits on day one.",
      choices: [
        { value: "documented" as const, label: "Written", hint: "Runnable plays people can follow" },
        { value: "mixed" as const, label: "Mixed", hint: "Some written, lots of tribal knowledge" },
        { value: "verbal" as const, label: "Mostly verbal", hint: "“Ask the owner” is still a workflow" },
      ],
    },
    quality: {
      title: "Does quality still ride on one pair of hands?",
      subtitle: "When the “right” plate still needs a specific person on the line.",
      choices: [
        { value: "yes" as const, label: "Yes" },
        { value: "no" as const, label: "No", hint: "Quality holds across people" },
        { value: "unsure" as const, label: "Not sure", hint: "Depends on the day" },
      ],
    },
  },

  escape: {
    metadataTitle: "Path off your plate",
    eyebrow: "Paced, not performative",
    title: "Path off your plate",
    desc:
      "Escape Readiness scores whether a week away is plausible from live procedures, training, owner dependencies, and staffing—then six guided moves to improve it.",
    noBizEyebrow: "Six moves",
    noBizTitle: "Path off your plate",
    noBizDesc:
      "Same arc lives here once the business is linked: capture plays, teach them, transfer calls, shrink approvals, test stability, then step back with proof.",
  },

  placeholders: {
    teamRouteTitle: "Backup on the floor",
    teamRoutePurpose:
      "One read on who can cover peaks, where teaching is thin, and when call-outs still hunt you—once roster depth is enabled for this workspace.",
    teamRouteBody:
      "This route is staged behind a feature flag. Your teaching data is still live under Who can carry what—use that until the roster-wide view ships here.",
    teamRoutePrimary: "Who can carry what",
    coachRouteTitle: "Outside read",
    coachRoutePurpose:
      "A structured brief from standards, teaching, shifts, and bottlenecks—optional signal, not a second dashboard.",
    coachRouteBody:
      "Outside read is disabled for this deployment. Rivet Index, execution proof, and bottlenecks stay on the main navigation.",
    coachRoutePrimary: "Workspace & account",
  },
} as const
